// ui/src/lib/components/admin/event-gallery-uploader.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { toast } from "svelte-sonner";

	import apiClient, { ApiError } from "$lib/api";
	import type { MediaFile } from "$lib/schemas/media";

	import { Button } from "$lib/components/ui/button";
	import { Card } from "$lib/components/ui/card";
	import { Progress } from "$lib/components/ui/progress";

	interface EventFolder {
		name: string;
		path: string;
	}

	interface Props {
		currentEventSlug?: string;
	}

	interface MediaResponse {
		files?: MediaFile[];
	}

	interface FolderResponse {
		folders?: EventFolder[];
	}

	interface UploadResponse {
		success?: boolean;
		files?: MediaFile[];
		totalUploaded?: number;
		totalFailed?: number;
		errors?: string[];
		message?: string;
	}

	let { currentEventSlug }: Props = $props();

	let eventFolders = $state<EventFolder[]>([]);
	let selectedEventSlug = $state("");

	let selectedFiles = $state<File[]>([]);
	let previews = $state<string[]>([]);

	let existingFiles = $state<MediaFile[]>([]);

	let loadingFolders = $state(true);
	let loadingFiles = $state(false);
	let uploading = $state(false);

	let deletingKey = $state<string | null>(null);
	let uploadProgress = $state(0);

	let fileInput: HTMLInputElement;

	onMount(() => {
		selectedEventSlug = currentEventSlug ?? "";
		void loadFolders();
	});

	$effect(() => {
		if (selectedEventSlug) {
			void loadExistingFiles(selectedEventSlug);
		} else {
			existingFiles = [];
		}
	});

	async function loadFolders() {
		loadingFolders = true;

		try {
			const response = await apiClient.get<FolderResponse>(
				"/admin/events/folders",
			);

			eventFolders = response.folders ?? [];
		} catch (error) {
			console.error("Failed to load event folders:", error);
			toast.error("Unable to load event folders.");
		} finally {
			loadingFolders = false;
		}
	}

	async function loadExistingFiles(slug: string) {
		loadingFiles = true;

		try {
			const response = await apiClient.get<MediaResponse>("/media");

			const galleryPrefix = `events/${slug}/gallery/`;

			existingFiles = (response.files ?? []).filter((file) =>
				file.key.startsWith(galleryPrefix),
			);
		} catch (error) {
			console.error("Failed to load event gallery:", error);
			toast.error("Unable to load the event gallery.");
		} finally {
			loadingFiles = false;
		}
	}

	function addFiles(files: FileList | File[]) {
		const incomingFiles = Array.from(files);

		const validFiles = incomingFiles.filter(
			(file) =>
				file.type.startsWith("image/") ||
				file.type.startsWith("video/"),
		);

		if (validFiles.length !== incomingFiles.length) {
			toast.error(
				"Some files were skipped. Only images and videos are allowed.",
			);
		}

		for (const file of validFiles) {
			selectedFiles.push(file);
			previews.push(URL.createObjectURL(file));
		}
	}

	function handleFileChange(event: Event) {
		const input = event.currentTarget as HTMLInputElement;

		if (input.files) {
			addFiles(input.files);
		}

		// Allows selecting the same file again later.
		input.value = "";
	}

	function handleDrop(event: DragEvent) {
		event.preventDefault();

		if (event.dataTransfer?.files) {
			addFiles(event.dataTransfer.files);
		}
	}

	function removeSelectedFile(index: number) {
		const preview = previews[index];

		if (preview) {
			URL.revokeObjectURL(preview);
		}

		selectedFiles = selectedFiles.filter(
			(_, fileIndex) => fileIndex !== index,
		);

		previews = previews.filter((_, fileIndex) => fileIndex !== index);
	}

	function clearSelectedFiles() {
		for (const preview of previews) {
			URL.revokeObjectURL(preview);
		}

		selectedFiles = [];
		previews = [];
	}

	async function uploadFiles() {
		if (!selectedEventSlug) {
			toast.error("Please select an event folder.");
			return;
		}

		if (selectedFiles.length === 0) {
			toast.error("Please select files to upload.");
			return;
		}

		uploading = true;
		uploadProgress = 0;

		try {
			const body = new FormData();

			body.append("eventSlug", selectedEventSlug);

			for (const file of selectedFiles) {
				// The Go batch endpoint expects repeated "files" fields.
				body.append("files", file, file.name);
			}

			const response = await apiClient.upload<UploadResponse>(
				"/admin/events/gallery/upload",
				body,
				({ percent }) => {
					uploadProgress = percent;
				},
			);

			const uploadedCount =
				response.totalUploaded ?? response.files?.length ?? 0;

			const failedCount = response.totalFailed ?? 0;

			if (failedCount > 0) {
				toast.warning(
					`Uploaded ${uploadedCount} file(s); ${failedCount} failed.`,
				);
			} else {
				toast.success(`Uploaded ${uploadedCount} file(s).`);
			}

			clearSelectedFiles();
			await loadExistingFiles(selectedEventSlug);
		} catch (error) {
			console.error("Failed to upload event gallery files:", error);

			if (error instanceof ApiError && error.status === 0) {
				toast.error(error.message);
			} else {
				toast.error("Failed to upload files.");
			}
		} finally {
			uploading = false;
		}
	}

	async function deleteFile(file: MediaFile) {
		const filename = file.key.split("/").pop() ?? "this file";

		if (!confirm(`Delete ${filename}?`)) {
			return;
		}

		deletingKey = file.key;

		try {
			await apiClient.delete("/admin/media/delete", {
				key: file.key,
			});

			toast.success("File deleted.");

			await loadExistingFiles(selectedEventSlug);
		} catch (error) {
			console.error("Failed to delete gallery file:", error);
			toast.error("Failed to delete file.");
		} finally {
			deletingKey = null;
		}
	}
</script>

<div class="space-y-6">
	<Card class="space-y-4 p-5">
		<div>
			<h2 class="text-lg font-semibold">Upload media</h2>

			<p class="text-sm text-muted-foreground">
				Select an event folder and upload images or videos to its
				gallery.
			</p>
		</div>

		<label class="space-y-2 text-sm font-medium">
			<span>Event folder</span>

			<select
				class="w-full rounded-md border bg-background px-3 py-2"
				bind:value={selectedEventSlug}
				disabled={loadingFolders || uploading}
			>
				<option value="">Choose an event…</option>

				{#each eventFolders as folder (folder.name)}
					<option value={folder.name}>
						{folder.name}
					</option>
				{/each}
			</select>
		</label>

		<div
			role="button"
			tabindex="0"
			class="cursor-pointer rounded-lg border-2 border-dashed p-8 text-center transition-colors hover:border-primary"
			onclick={() => fileInput?.click()}
			onkeydown={(event) => {
				if (event.key === "Enter" || event.key === " ") {
					fileInput?.click();
				}
			}}
			ondragover={(event) => event.preventDefault()}
			ondrop={handleDrop}
		>
			<p class="text-3xl" aria-hidden="true">↥</p>

			<p class="text-sm text-muted-foreground">
				Click to upload or drag and drop
			</p>

			<p class="mt-1 text-xs text-muted-foreground">
				Images and videos only
			</p>
		</div>

		<input
			bind:this={fileInput}
			type="file"
			multiple
			accept="image/*,video/*"
			class="hidden"
			onchange={handleFileChange}
			disabled={uploading}
		/>

		{#if selectedFiles.length > 0}
			<div class="space-y-3">
				<div class="flex items-center justify-between">
					<h3 class="text-sm font-medium">
						Selected files ({selectedFiles.length})
					</h3>

					<Button
						type="button"
						variant="ghost"
						size="sm"
						onclick={clearSelectedFiles}
						disabled={uploading}
					>
						Clear all
					</Button>
				</div>

				<div class="grid grid-cols-2 gap-4 md:grid-cols-4">
					{#each selectedFiles as file, index (file.name + file.lastModified + index)}
						<div class="group relative min-w-0">
							<div
								class="aspect-square overflow-hidden rounded-lg bg-muted"
							>
								{#if file.type.startsWith("image/")}
									<img
										src={previews[index]}
										alt={file.name}
										class="h-full w-full object-cover"
									/>
								{:else}
									<div
										class="flex h-full items-center justify-center text-3xl"
										aria-label="Video file"
									>
										▶
									</div>
								{/if}
							</div>

							<button
								type="button"
								class="absolute right-2 top-2 rounded-full bg-destructive px-2 py-1 text-xs text-destructive-foreground"
								onclick={() => removeSelectedFile(index)}
								disabled={uploading}
								aria-label={`Remove ${file.name}`}
							>
								×
							</button>

							<p class="mt-1 truncate text-xs" title={file.name}>
								{file.name}
							</p>
						</div>
					{/each}
				</div>
			</div>
		{/if}

		{#if uploading}
			<div class="space-y-2">
				<div class="flex justify-between text-sm">
					<span>Uploading…</span>
					<span>{uploadProgress}%</span>
				</div>

				<Progress value={uploadProgress} />
			</div>
		{/if}

		<Button
			type="button"
			class="w-full"
			onclick={uploadFiles}
			disabled={!selectedEventSlug ||
				selectedFiles.length === 0 ||
				uploading}
		>
			{uploading
				? "Uploading…"
				: `Upload ${
						selectedFiles.length
							? `${selectedFiles.length} file(s)`
							: "files"
					}`}
		</Button>
	</Card>

	{#if selectedEventSlug}
		<Card class="space-y-4 p-5">
			<div>
				<h2 class="text-lg font-semibold">Existing gallery</h2>

				<p class="text-sm text-muted-foreground">
					{existingFiles.length} file(s) in
					{selectedEventSlug}/gallery
				</p>
			</div>

			{#if loadingFiles}
				<p class="py-8 text-center text-sm text-muted-foreground">
					Loading gallery…
				</p>
			{:else if existingFiles.length === 0}
				<p class="py-8 text-center text-sm text-muted-foreground">
					No files in this gallery yet.
				</p>
			{:else}
				<div
					class="grid grid-cols-2 gap-4 md:grid-cols-4 lg:grid-cols-6"
				>
					{#each existingFiles as file (file.key)}
						<div class="group relative min-w-0">
							<div
								class="aspect-square overflow-hidden rounded-lg bg-muted"
							>
								{#if file.type === "image"}
									<img
										src={file.url}
										alt={file.key}
										class="h-full w-full object-cover"
										loading="lazy"
									/>
								{:else if file.type === "video"}
									<video
										src={file.url}
										class="h-full w-full object-cover"
										controls
										preload="metadata"
									>
										<track kind="captions" />
									</video>
								{:else}
									<div
										class="flex h-full items-center justify-center text-3xl"
										aria-label="Other media file"
									>
										📄
									</div>
								{/if}
							</div>

							<button
								type="button"
								class="absolute right-2 top-2 rounded-full bg-destructive px-2 py-1 text-xs text-destructive-foreground"
								onclick={() => deleteFile(file)}
								disabled={deletingKey !== null}
								aria-label={`Delete ${file.key}`}
							>
								×
							</button>

							<p class="mt-1 truncate text-xs" title={file.key}>
								{file.key.split("/").pop()}
							</p>
						</div>
					{/each}
				</div>
			{/if}
		</Card>
	{/if}
</div>

// src/components/admin/event-gallery-uploader.tsx
import { useState, useRef, useCallback } from 'react';
import { Button } from '~/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '~/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '~/components/ui/select';
import { Progress } from '~/components/ui/progress';
import { Image } from '~/components/ui/image';
import { galleryService } from '~/lib/services/gallery-service';
import { Upload, X, Loader2, ImageIcon, Video, Trash2 } from 'lucide-react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { apiClient } from '~/lib/api';

interface EventGalleryUploaderProps {
	currentEventSlug?: string;
}

export function EventGalleryUploader({ currentEventSlug }: EventGalleryUploaderProps) {
	const [selectedEventSlug, setSelectedEventSlug] = useState<string>(currentEventSlug || '');
	const [selectedFiles, setSelectedFiles] = useState<File[]>([]);
	const [uploadProgress, setUploadProgress] = useState(0);
	const [previews, setPreviews] = useState<string[]>([]);
	const fileInputRef = useRef<HTMLInputElement>(null);
	const queryClient = useQueryClient();

	// Fetch event folders
	const { data: eventFolders = [], isLoading: loadingFolders } = useQuery({
		queryKey: ['eventFolders'],
		queryFn: () => galleryService.getEventFolders(),
	});

	// Fetch existing gallery images for selected event
	const { data: existingImages = [], isLoading: loadingImages, refetch: refetchImages } = useQuery({
		queryKey: ['eventGallery', selectedEventSlug],
		queryFn: () => galleryService.getEventGallery(selectedEventSlug),
		enabled: !!selectedEventSlug,
	});

	// Upload mutation
	const uploadMutation = useMutation({
		mutationFn: async (files: File[]) => {
			return galleryService.uploadMultipleToEventGallery(
				selectedEventSlug,
				files,
				setUploadProgress
			);
		},
		onSuccess: (uploadedFiles) => {
			toast.success(`Successfully uploaded ${uploadedFiles.length} file(s)`);
			setSelectedFiles([]);
			setPreviews([]);
			setUploadProgress(0);
			refetchImages();
			queryClient.invalidateQueries({ queryKey: ['eventGallery', selectedEventSlug] });
		},
		onError: (error) => {
			toast.error('Failed to upload files');
			console.error(error);
		},
	});

	// Delete mutation
	const deleteMutation = useMutation({
		mutationFn: async (fileKey: string) => {
			await apiClient.delete('/admin/media/delete', {
				data: { key: fileKey },
			});
		},
		onSuccess: () => {
			toast.success('File deleted successfully');
			refetchImages();
			queryClient.invalidateQueries({ queryKey: ['eventGallery', selectedEventSlug] });
		},
		onError: (error) => {
			toast.error('Failed to delete file');
			console.error(error);
		},
	});

	const handleFileSelect = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
		const files = Array.from(e.target.files || []);
		if (files.length === 0) return;

		// Validate file types
		const validFiles = files.filter(file => {
			const isImage = file.type.startsWith('image/');
			const isVideo = file.type.startsWith('video/');
			return isImage || isVideo;
		});

		if (validFiles.length !== files.length) {
			toast.error('Some files were skipped. Only images and videos are allowed.');
		}

		setSelectedFiles(prev => [...prev, ...validFiles]);

		// Generate previews
		validFiles.forEach(file => {
			const reader = new FileReader();
			reader.onloadend = () => {
				setPreviews(prev => [...prev, reader.result as string]);
			};
			reader.readAsDataURL(file);
		});

		// Reset input
		if (e.target) {
			e.target.value = '';
		}
	}, []);

	const handleRemoveFile = useCallback((index: number) => {
		setSelectedFiles(prev => prev.filter((_, i) => i !== index));
		setPreviews(prev => prev.filter((_, i) => i !== index));
	}, []);

	const handleUpload = useCallback(() => {
		if (!selectedEventSlug) {
			toast.error('Please select an event folder');
			return;
		}

		if (selectedFiles.length === 0) {
			toast.error('Please select files to upload');
			return;
		}

		uploadMutation.mutate(selectedFiles);
	}, [selectedEventSlug, selectedFiles, uploadMutation]);

	const handleDelete = useCallback((fileKey: string) => {
		if (confirm('Are you sure you want to delete this file?')) {
			deleteMutation.mutate(fileKey);
		}
	}, [deleteMutation]);

	const isUploading = uploadMutation.isPending;

	return (
		<div className="space-y-6">
			{/* Upload Section */}
			<Card>
				<CardHeader>
					<CardTitle>Upload Media</CardTitle>
					<CardDescription>
						Select an event folder and upload images or videos to its gallery.
					</CardDescription>
				</CardHeader>
				<CardContent className="space-y-4">
					{/* Event Folder Selector */}
					<div className="space-y-2">
						<label className="text-sm font-medium">Select Event Folder</label>
						<Select
							value={selectedEventSlug}
							onValueChange={setSelectedEventSlug}
							disabled={loadingFolders || isUploading}
						>
							<SelectTrigger>
								<SelectValue placeholder="Choose an event..." />
							</SelectTrigger>
							<SelectContent>
								{eventFolders.map((folder) => (
									<SelectItem key={folder.name} value={folder.name}>
										{folder.name}
									</SelectItem>
								))}
							</SelectContent>
						</Select>
					</div>

					{/* File Upload Area */}
					<div className="space-y-2">
						<label className="text-sm font-medium">Select Files</label>
						<div
							className="border-2 border-dashed rounded-lg p-8 text-center cursor-pointer hover:border-primary transition-colors"
							onClick={() => fileInputRef.current?.click()}
						>
							<Upload className="w-12 h-12 mx-auto mb-4 text-muted-foreground" />
							<p className="text-sm text-muted-foreground mb-2">
								Click to upload or drag and drop
							</p>
							<p className="text-xs text-muted-foreground">
								Images (JPG, PNG, GIF, WebP) and Videos (MP4, WebM, MOV)
							</p>
						</div>
						<input
							ref={fileInputRef}
							type="file"
							multiple
							accept="image/*,video/*"
							className="hidden"
							onChange={handleFileSelect}
							disabled={isUploading}
						/>
					</div>

					{/* Selected Files Preview */}
					{selectedFiles.length > 0 && (
						<div className="space-y-2">
							<label className="text-sm font-medium">
								Selected Files ({selectedFiles.length})
							</label>
							<div className="grid grid-cols-2 md:grid-cols-4 gap-4">
								{selectedFiles.map((file, index) => (
									<div key={index} className="relative group">
										<div className="aspect-square rounded-lg overflow-hidden bg-muted">
											{file.type.startsWith('image/') ? (
												<img
													src={previews[index]}
													alt={file.name}
													className="w-full h-full object-cover"
												/>
											) : (
												<div className="w-full h-full flex items-center justify-center">
													<Video className="w-8 h-8 text-muted-foreground" />
												</div>
											)}
										</div>
										<button
											onClick={() => handleRemoveFile(index)}
											className="absolute top-2 right-2 p-1 bg-destructive text-destructive-foreground rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
											disabled={isUploading}
										>
											<X className="w-4 h-4" />
										</button>
										<p className="text-xs mt-1 truncate" title={file.name}>
											{file.name}
										</p>
									</div>
								))}
							</div>
						</div>
					)}

					{/* Upload Progress */}
					{isUploading && (
						<div className="space-y-2">
							<div className="flex justify-between text-sm">
								<span>Uploading...</span>
								<span>{Math.round(uploadProgress)}%</span>
							</div>
							<Progress value={uploadProgress} />
						</div>
					)}

					{/* Upload Button */}
					<Button
						onClick={handleUpload}
						disabled={!selectedEventSlug || selectedFiles.length === 0 || isUploading}
						className="w-full"
					>
						{isUploading ? (
							<>
								<Loader2 className="mr-2 w-4 h-4 animate-spin" />
								Uploading...
							</>
						) : (
							<>
								<Upload className="mr-2 w-4 h-4" />
								Upload {selectedFiles.length > 0 ? `${selectedFiles.length} file(s)` : ''}
							</>
						)}
					</Button>
				</CardContent>
			</Card>

			{/* Existing Gallery Section */}
			{selectedEventSlug && (
				<Card>
					<CardHeader>
						<CardTitle>Existing Gallery</CardTitle>
						<CardDescription>
							{existingImages.length} file(s) in {selectedEventSlug}/gallery
						</CardDescription>
					</CardHeader>
					<CardContent>
						{loadingImages ? (
							<div className="flex justify-center py-8">
								<Loader2 className="w-8 h-8 animate-spin" />
							</div>
						) : existingImages.length === 0 ? (
							<div className="text-center py-8 text-muted-foreground">
								<ImageIcon className="w-12 h-12 mx-auto mb-2 opacity-50" />
								<p>No files in gallery yet</p>
							</div>
						) : (
							<div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">
								{existingImages.map((file) => (
									<div key={file.key} className="relative group">
										<div className="aspect-square rounded-lg overflow-hidden bg-muted">
											{file.type === 'image' ? (
												<Image
													src={file.url}
													alt={file.key}
													className="w-full h-full object-cover"
												/>
											) : (
												<div className="w-full h-full flex items-center justify-center">
													<Video className="w-8 h-8 text-muted-foreground" />
												</div>
											)}
										</div>
										<button
											onClick={() => handleDelete(file.key)}
											className="absolute top-2 right-2 p-1.5 bg-destructive text-destructive-foreground rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
											disabled={deleteMutation.isPending}
										>
											<Trash2 className="w-3 h-3" />
										</button>
										<p className="text-xs mt-1 truncate" title={file.key}>
											{file.key.split('/').pop()}
										</p>
									</div>
								))}
							</div>
						)}
					</CardContent>
				</Card>
			)}
		</div>
	);
}
