// ui/src/lib/components/admin/submission-review.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { toast } from "svelte-sonner";

	import apiClient from "$lib/api";
	import type { VehicleSubmission } from "$lib/schemas/event";

	import { Button } from "$lib/components/ui/button";
	import { Card } from "$lib/components/ui/card";
	import { Textarea } from "$lib/components/ui/textarea";

	interface Props {
		eventId: string;
		eventName: string;
	}

	interface SubmissionsResponse {
		submissions?: VehicleSubmission[];
	}

	let { eventId, eventName }: Props = $props();

	let submissions = $state<VehicleSubmission[]>([]);
	let selectedSubmission = $state<VehicleSubmission | null>(null);

	let activeTab = $state<"pending" | "reviewed">("pending");
	let currentImageIndex = $state(0);

	let loading = $state(true);
	let processing = $state(false);
	let errorMessage = $state("");

	let action = $state<"approve" | "deny" | null>(null);
	let actionNotes = $state("");

	const pendingSubmissions = $derived(
		submissions.filter((submission) => submission.status === "pending"),
	);

	const reviewedSubmissions = $derived(
		submissions.filter((submission) => submission.status !== "pending"),
	);

	const visibleSubmissions = $derived(
		activeTab === "pending" ? pendingSubmissions : reviewedSubmissions,
	);

	onMount(() => {
		void loadSubmissions();
	});

	function formatDate(value?: string): string {
		if (!value) return "—";

		return new Intl.DateTimeFormat(undefined, {
			dateStyle: "medium",
		}).format(new Date(value));
	}

	async function loadSubmissions() {
		loading = true;
		errorMessage = "";

		try {
			const response = await apiClient.get<SubmissionsResponse>(
				`/admin/submissions/${eventId}`,
			);

			submissions = response.submissions ?? [];
		} catch (error) {
			console.error("Failed to load submissions:", error);
			errorMessage = "Failed to load submissions.";
		} finally {
			loading = false;
		}
	}

	function openSubmission(submission: VehicleSubmission) {
		selectedSubmission = submission;
		currentImageIndex = 0;
		action = null;
		actionNotes = "";
	}

	function closeSubmission() {
		selectedSubmission = null;
		action = null;
		actionNotes = "";
	}

	function showPreviousImage() {
		if (!selectedSubmission) return;

		currentImageIndex =
			currentImageIndex === 0
				? selectedSubmission.images.length - 1
				: currentImageIndex - 1;
	}

	function showNextImage() {
		if (!selectedSubmission) return;

		currentImageIndex =
			currentImageIndex === selectedSubmission.images.length - 1
				? 0
				: currentImageIndex + 1;
	}

	async function submitAction() {
		if (!selectedSubmission || !action) return;

		if (action === "deny" && !actionNotes.trim()) {
			toast.error("A reason is required when denying a submission.");
			return;
		}

		processing = true;

		try {
			const endpoint =
				action === "approve"
					? `/admin/submissions/${selectedSubmission.id}/approve`
					: `/admin/submissions/${selectedSubmission.id}/deny`;

			await apiClient.put(endpoint, {
				notes: actionNotes.trim(),
			});

			toast.success(
				action === "approve"
					? "Submission approved."
					: "Submission denied.",
			);

			closeSubmission();
			await loadSubmissions();
		} catch (error) {
			console.error("Failed to update submission:", error);
			toast.error(
				action === "approve"
					? "Failed to approve submission."
					: "Failed to deny submission.",
			);
		} finally {
			processing = false;
		}
	}
</script>

{#if loading}
	<div
		class="flex min-h-64 items-center justify-center text-muted-foreground"
	>
		Loading submissions…
	</div>
{:else}
	<div class="space-y-6">
		<div>
			<h2 class="text-2xl font-bold">Vehicle submissions</h2>

			<p class="text-muted-foreground">
				Review and approve participant vehicles for {eventName}.
			</p>
		</div>

		{#if errorMessage}
			<p
				role="alert"
				class="rounded-xl border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive"
			>
				{errorMessage}
			</p>
		{/if}

		<div class="flex gap-2 border-b">
			<Button
				type="button"
				variant={activeTab === "pending" ? "default" : "ghost"}
				onclick={() => (activeTab = "pending")}
			>
				Pending review ({pendingSubmissions.length})
			</Button>

			<Button
				type="button"
				variant={activeTab === "reviewed" ? "default" : "ghost"}
				onclick={() => (activeTab = "reviewed")}
			>
				Reviewed ({reviewedSubmissions.length})
			</Button>
		</div>

		{#if visibleSubmissions.length === 0}
			<Card class="p-8 text-center text-muted-foreground">
				No {activeTab} submissions.
			</Card>
		{:else}
			<div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
				{#each visibleSubmissions as submission (submission.id)}
					<button
						type="button"
						class="text-left"
						onclick={() => openSubmission(submission)}
					>
						<Card
							class="h-full space-y-4 p-4 transition-shadow hover:shadow-lg"
						>
							<div class="flex items-start justify-between gap-3">
								<div>
									<h3 class="font-semibold">
										{submission.vehicle_year}
										{submission.vehicle_make}
										{submission.vehicle_model}
									</h3>

									<p class="text-sm text-muted-foreground">
										{submission.participant_name}
									</p>
								</div>

								<span
									class="rounded-full border px-2 py-1 text-xs capitalize"
								>
									{submission.status}
								</span>
							</div>

							{#if submission.images[0]}
								<img
									src={submission.images[0]}
									alt={`${submission.vehicle_make} ${submission.vehicle_model}`}
									class="aspect-video w-full rounded-lg object-cover"
								/>
							{:else}
								<div
									class="flex aspect-video items-center justify-center rounded-lg bg-muted text-sm text-muted-foreground"
								>
									No vehicle images
								</div>
							{/if}

							<p class="text-sm text-muted-foreground">
								Submitted
								{formatDate(submission.submitted_at)}
							</p>
						</Card>
					</button>
				{/each}
			</div>
		{/if}
	</div>
{/if}

{#if selectedSubmission}
	<div
		class="fixed inset-0 z-50 overflow-y-auto bg-background/80 p-4 backdrop-blur-sm"
	>
		<div class="mx-auto max-w-4xl">
			<Card class="space-y-6 p-5">
				<div class="flex items-start justify-between gap-4">
					<div>
						<h2 class="text-xl font-semibold">
							{selectedSubmission.vehicle_year}
							{selectedSubmission.vehicle_make}
							{selectedSubmission.vehicle_model}
						</h2>

						<p class="text-sm text-muted-foreground">
							Submitted by
							{selectedSubmission.participant_name}
						</p>
					</div>

					<Button
						type="button"
						variant="ghost"
						onclick={closeSubmission}
					>
						Close
					</Button>
				</div>

				{#if selectedSubmission.images.length > 0}
					<div class="space-y-3">
						<img
							src={selectedSubmission.images[currentImageIndex]}
							alt={`Vehicle image ${currentImageIndex + 1}`}
							class="max-h-[28rem] w-full rounded-lg object-contain"
						/>

						{#if selectedSubmission.images.length > 1}
							<div class="flex items-center justify-center gap-3">
								<Button
									type="button"
									variant="outline"
									onclick={showPreviousImage}
								>
									Previous
								</Button>

								<span class="text-sm">
									{currentImageIndex + 1} /
									{selectedSubmission.images.length}
								</span>

								<Button
									type="button"
									variant="outline"
									onclick={showNextImage}
								>
									Next
								</Button>
							</div>
						{/if}
					</div>
				{/if}

				<div class="grid gap-6 md:grid-cols-2">
					<div>
						<h3 class="font-semibold">Participant</h3>

						<p>{selectedSubmission.participant_name}</p>

						<a
							class="text-sm text-primary hover:underline"
							href={`mailto:${selectedSubmission.participant_email}`}
						>
							{selectedSubmission.participant_email}
						</a>

						{#if selectedSubmission.participant_phone}
							<p>{selectedSubmission.participant_phone}</p>
						{/if}
					</div>

					<div>
						<h3 class="font-semibold">Vehicle</h3>

						<p>
							{selectedSubmission.vehicle_year}
							{selectedSubmission.vehicle_make}
							{selectedSubmission.vehicle_model}
						</p>

						<p class="text-sm text-muted-foreground">
							Submitted
							{formatDate(selectedSubmission.submitted_at)}
						</p>
					</div>
				</div>

				{#if selectedSubmission.vehicle_description}
					<div>
						<h3 class="font-semibold">Description</h3>

						<p
							class="whitespace-pre-wrap text-sm text-muted-foreground"
						>
							{selectedSubmission.vehicle_description}
						</p>
					</div>
				{/if}

				{#if selectedSubmission.vehicle_modifications}
					<div>
						<h3 class="font-semibold">Modifications</h3>

						<p
							class="whitespace-pre-wrap text-sm text-muted-foreground"
						>
							{selectedSubmission.vehicle_modifications}
						</p>
					</div>
				{/if}

				{#if selectedSubmission.review_notes}
					<div
						class="rounded-xl border border-primary/30 bg-primary/5 p-4"
					>
						<h3 class="font-semibold">Review notes</h3>

						<p class="whitespace-pre-wrap text-sm">
							{selectedSubmission.review_notes}
						</p>
					</div>
				{/if}

				{#if selectedSubmission.status === "pending"}
					{#if action}
						<div class="space-y-3 rounded-xl border p-4">
							<h3 class="font-semibold">
								{action === "approve" ? "Approve" : "Deny"}
								submission
							</h3>

							<p class="text-sm text-muted-foreground">
								{action === "approve"
									? "Approval notes are optional."
									: "A reason is required when denying a submission."}
							</p>

							<Textarea
								bind:value={actionNotes}
								placeholder={action === "approve"
									? "Optional approval notes"
									: "Reason for denial"}
								rows={4}
							/>

							<div class="flex justify-end gap-2">
								<Button
									type="button"
									variant="ghost"
									onclick={() => {
										action = null;
										actionNotes = "";
									}}
									disabled={processing}
								>
									Cancel
								</Button>

								<Button
									type="button"
									variant={action === "deny"
										? "destructive"
										: "default"}
									onclick={submitAction}
									disabled={processing ||
										(action === "deny" &&
											!actionNotes.trim())}
								>
									{processing
										? "Processing…"
										: action === "approve"
											? "Approve"
											: "Deny"}
								</Button>
							</div>
						</div>
					{:else}
						<div class="flex justify-end gap-2">
							<Button
								type="button"
								variant="outline"
								onclick={() => (action = "deny")}
							>
								Deny
							</Button>

							<Button
								type="button"
								onclick={() => (action = "approve")}
							>
								Approve
							</Button>
						</div>
					{/if}
				{/if}
			</Card>
		</div>
	</div>
{/if}

// src/components/admin/submission-review.tsx
import React, { useState, useEffect } from 'react';
import { format } from 'date-fns';
import {
	Car,
	CheckCircle,
	XCircle,
	Clock,
	Mail,
	Phone,
	Calendar,
	User,
	Image as ImageIcon,
	ChevronLeft,
	ChevronRight,
	Loader2,
	AlertCircle,
} from 'lucide-react';
import { Button } from '~/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '~/components/ui/card';
import { Badge } from '~/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '~/components/ui/dialog';
import { Textarea } from '~/components/ui/textarea';
import { Label } from '~/components/ui/label';
import { Alert, AlertDescription } from '~/components/ui/alert';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '~/components/ui/tabs';
import { submissionService } from '~/lib/services/submission-service';
import type { VehicleSubmission } from '~/lib/interfaces/submission';

interface SubmissionReviewProps {
	eventId: string;
	eventName: string;
}

export function SubmissionReview({ eventId, eventName }: SubmissionReviewProps) {
	const [submissions, setSubmissions] = useState<VehicleSubmission[]>([]);
	const [selectedSubmission, setSelectedSubmission] = useState<VehicleSubmission | null>(null);
	const [currentImageIndex, setCurrentImageIndex] = useState(0);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState<string | null>(null);
	const [actionDialog, setActionDialog] = useState<{
		open: boolean;
		type: 'approve' | 'deny' | null;
		submission: VehicleSubmission | null;
	}>({ open: false, type: null, submission: null });
	const [actionNotes, setActionNotes] = useState('');
	const [processing, setProcessing] = useState(false);

	useEffect(() => {
		loadSubmissions();
	}, [eventId]);

	const loadSubmissions = async () => {
		try {
			setLoading(true);
			const data = await submissionService.getEventSubmissions(eventId);
			setSubmissions(data);
			setError(null);
		} catch (err) {
			setError('Failed to load submissions');
			console.error(err);
		} finally {
			setLoading(false);
		}
	};

	const handleAction = async () => {
		if (!actionDialog.submission || !actionDialog.type) return;

		setProcessing(true);
		try {
			if (actionDialog.type === 'approve') {
				await submissionService.approveSubmission(actionDialog.submission.id, actionNotes);
			} else {
				await submissionService.denySubmission(actionDialog.submission.id, actionNotes);
			}

			// Reload submissions
			await loadSubmissions();

			// Close dialog and reset
			setActionDialog({ open: false, type: null, submission: null });
			setActionNotes('');
			setSelectedSubmission(null);
		} catch (err) {
			setError(`Failed to ${actionDialog.type} submission`);
		} finally {
			setProcessing(false);
		}
	};

	const getStatusBadge = (status: VehicleSubmission['status']) => {
		switch (status) {
			case 'pending':
				return <Badge variant="secondary"><Clock className="w-3 h-3 mr-1" />Pending Review</Badge>;
			case 'approved':
				return <Badge variant="default" className="bg-green-500"><CheckCircle className="w-3 h-3 mr-1" />Approved</Badge>;
			case 'denied':
				return <Badge variant="destructive"><XCircle className="w-3 h-3 mr-1" />Denied</Badge>;
		}
	};

	const pendingSubmissions = submissions.filter(s => s.status === 'pending');
	const reviewedSubmissions = submissions.filter(s => s.status !== 'pending');

	if (loading) {
		return (
			<div className="flex items-center justify-center h-64">
				<Loader2 className="w-8 h-8 animate-spin" />
			</div>
		);
	}

	return (
		<div className="space-y-6">
			<div>
				<h2 className="text-2xl font-bold">Vehicle Submissions</h2>
				<p className="text-muted-foreground">Review and approve participant vehicles for {eventName}</p>
			</div>

			{error && (
				<Alert variant="destructive">
					<AlertCircle className="h-4 w-4" />
					<AlertDescription>{error}</AlertDescription>
				</Alert>
			)}

			<Tabs defaultValue="pending" className="w-full">
				<TabsList className="grid w-full grid-cols-2">
					<TabsTrigger value="pending">
						Pending Review ({pendingSubmissions.length})
					</TabsTrigger>
					<TabsTrigger value="reviewed">
						Reviewed ({reviewedSubmissions.length})
					</TabsTrigger>
				</TabsList>

				<TabsContent value="pending" className="space-y-4">
					{pendingSubmissions.length === 0 ? (
						<Card>
							<CardContent className="text-center py-8">
								<Car className="w-12 h-12 mx-auto text-muted-foreground mb-4" />
								<p className="text-muted-foreground">No pending submissions</p>
							</CardContent>
						</Card>
					) : (
						<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
							{pendingSubmissions.map((submission) => (
								<Card
									key={submission.id}
									className="cursor-pointer hover:shadow-lg transition-shadow"
									onClick={() => setSelectedSubmission(submission)}
								>
									<CardHeader>
										<div className="flex justify-between items-start">
											<div>
												<CardTitle className="text-lg">
													{submission.vehicleYear} {submission.vehicleMake} {submission.vehicleModel}
												</CardTitle>
												<CardDescription>{submission.participantName}</CardDescription>
											</div>
											{getStatusBadge(submission.status)}
										</div>
									</CardHeader>
									<CardContent>
										<div className="aspect-video relative overflow-hidden rounded-lg bg-gray-100">
											{submission.images[0] ? (
												<img
													src={submission.images[0]}
													alt={`${submission.vehicleMake} ${submission.vehicleModel}`}
													className="object-cover w-full h-full"
												/>
											) : (
												<div className="flex items-center justify-center h-full">
													<ImageIcon className="w-8 h-8 text-gray-400" />
												</div>
											)}
										</div>
										<div className="mt-4 flex items-center text-sm text-muted-foreground">
											<Calendar className="w-4 h-4 mr-1" />
											{format(new Date(submission.submittedAt), 'MMM dd, yyyy')}
										</div>
									</CardContent>
								</Card>
							))}
						</div>
					)}
				</TabsContent>

				<TabsContent value="reviewed" className="space-y-4">
					{reviewedSubmissions.length === 0 ? (
						<Card>
							<CardContent className="text-center py-8">
								<CheckCircle className="w-12 h-12 mx-auto text-muted-foreground mb-4" />
								<p className="text-muted-foreground">No reviewed submissions yet</p>
							</CardContent>
						</Card>
					) : (
						<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
							{reviewedSubmissions.map((submission) => (
								<Card
									key={submission.id}
									className="cursor-pointer hover:shadow-lg transition-shadow"
									onClick={() => setSelectedSubmission(submission)}
								>
									<CardHeader>
										<div className="flex justify-between items-start">
											<div>
												<CardTitle className="text-lg">
													{submission.vehicleYear} {submission.vehicleMake} {submission.vehicleModel}
												</CardTitle>
												<CardDescription>{submission.participantName}</CardDescription>
											</div>
											{getStatusBadge(submission.status)}
										</div>
									</CardHeader>
									<CardContent>
										<div className="aspect-video relative overflow-hidden rounded-lg bg-gray-100">
											{submission.images[0] ? (
												<img
													src={submission.images[0]}
													alt={`${submission.vehicleMake} ${submission.vehicleModel}`}
													className="object-cover w-full h-full"
												/>
											) : (
												<div className="flex items-center justify-center h-full">
													<ImageIcon className="w-8 h-8 text-gray-400" />
												</div>
											)}
										</div>
										<div className="mt-4 space-y-1">
											<div className="flex items-center text-sm text-muted-foreground">
												<Calendar className="w-4 h-4 mr-1" />
												Submitted: {format(new Date(submission.submittedAt), 'MMM dd, yyyy')}
											</div>
											{submission.reviewedAt && (
												<div className="flex items-center text-sm text-muted-foreground">
													<Clock className="w-4 h-4 mr-1" />
													Reviewed: {format(new Date(submission.reviewedAt), 'MMM dd, yyyy')}
												</div>
											)}
										</div>
									</CardContent>
								</Card>
							))}
						</div>
					)}
				</TabsContent>
			</Tabs>

			{/* Submission Detail Dialog */}
			<Dialog open={!!selectedSubmission} onOpenChange={() => setSelectedSubmission(null)}>
				<DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
					{selectedSubmission && (
						<>
							<DialogHeader>
								<DialogTitle>
									{selectedSubmission.vehicleYear} {selectedSubmission.vehicleMake} {selectedSubmission.vehicleModel}
								</DialogTitle>
								<DialogDescription>
									Submission by {selectedSubmission.participantName}
								</DialogDescription>
							</DialogHeader>

							<div className="space-y-6">
								{/* Image Gallery */}
								<div className="space-y-4">
									<div className="aspect-video relative overflow-hidden rounded-lg bg-gray-100">
										<img
											src={selectedSubmission.images[currentImageIndex]}
											alt={`Vehicle image ${currentImageIndex + 1}`}
											className="object-contain w-full h-full"
										/>
										{selectedSubmission.images.length > 1 && (
											<>
												<Button
													variant="ghost"
													size="icon"
													className="absolute left-2 top-1/2 -translate-y-1/2"
													onClick={(e) => {
														e.stopPropagation();
														setCurrentImageIndex((prev) =>
															prev === 0 ? selectedSubmission.images.length - 1 : prev - 1
														);
													}}
												>
													<ChevronLeft className="h-4 w-4" />
												</Button>
												<Button
													variant="ghost"
													size="icon"
													className="absolute right-2 top-1/2 -translate-y-1/2"
													onClick={(e) => {
														e.stopPropagation();
														setCurrentImageIndex((prev) =>
															prev === selectedSubmission.images.length - 1 ? 0 : prev + 1
														);
													}}
												>
													<ChevronRight className="h-4 w-4" />
												</Button>
											</>
										)}
									</div>
									{selectedSubmission.images.length > 1 && (
										<div className="flex gap-2 justify-center">
											{selectedSubmission.images.map((_, index) => (
												<button
													key={index}
													className={`w-2 h-2 rounded-full transition-colors ${index === currentImageIndex ? 'bg-primary' : 'bg-gray-300'
														}`}
													onClick={() => setCurrentImageIndex(index)}
												/>
											))}
										</div>
									)}
								</div>

								{/* Participant Details */}
								<div className="grid grid-cols-1 md:grid-cols-2 gap-4">
									<div className="space-y-2">
										<h3 className="font-semibold">Participant Information</h3>
										<div className="space-y-1">
											<div className="flex items-center gap-2 text-sm">
												<User className="w-4 h-4 text-muted-foreground" />
												<span>{selectedSubmission.participantName}</span>
											</div>
											<div className="flex items-center gap-2 text-sm">
												<Mail className="w-4 h-4 text-muted-foreground" />
												<a href={`mailto:${selectedSubmission.participantEmail}`} className="text-primary hover:underline">
													{selectedSubmission.participantEmail}
												</a>
											</div>
											{selectedSubmission.participantPhone && (
												<div className="flex items-center gap-2 text-sm">
													<Phone className="w-4 h-4 text-muted-foreground" />
													<a href={`tel:${selectedSubmission.participantPhone}`} className="text-primary hover:underline">
														{selectedSubmission.participantPhone}
													</a>
												</div>
											)}
										</div>
									</div>

									<div className="space-y-2">
										<h3 className="font-semibold">Vehicle Details</h3>
										<div className="space-y-1 text-sm">
											<div>
												<span className="font-medium">Year:</span> {selectedSubmission.vehicleYear}
											</div>
											<div>
												<span className="font-medium">Make:</span> {selectedSubmission.vehicleMake}
											</div>
											<div>
												<span className="font-medium">Model:</span> {selectedSubmission.vehicleModel}
											</div>
										</div>
									</div>
								</div>

								{selectedSubmission.vehicleDescription && (
									<div className="space-y-2">
										<h3 className="font-semibold">Description</h3>
										<p className="text-sm text-muted-foreground">{selectedSubmission.vehicleDescription}</p>
									</div>
								)}

								{selectedSubmission.vehicleModifications && (
									<div className="space-y-2">
										<h3 className="font-semibold">Modifications</h3>
										<p className="text-sm text-muted-foreground">{selectedSubmission.vehicleModifications}</p>
									</div>
								)}

								{selectedSubmission.reviewNotes && (
									<Alert>
										<AlertCircle className="h-4 w-4" />
										<AlertDescription>
											<strong>Review Notes:</strong> {selectedSubmission.reviewNotes}
										</AlertDescription>
									</Alert>
								)}

								{/* Actions */}
								{selectedSubmission.status === 'pending' && (
									<div className="flex gap-2 justify-end">
										<Button
											variant="outline"
											onClick={() => {
												setActionDialog({
													open: true,
													type: 'deny',
													submission: selectedSubmission,
												});
											}}
										>
											<XCircle className="w-4 h-4 mr-2" />
											Deny
										</Button>
										<Button
											onClick={() => {
												setActionDialog({
													open: true,
													type: 'approve',
													submission: selectedSubmission,
												});
											}}
										>
											<CheckCircle className="w-4 h-4 mr-2" />
											Approve
										</Button>
									</div>
								)}
							</div>
						</>
					)}
				</DialogContent>
			</Dialog>

			{/* Action Confirmation Dialog */}
			<Dialog open={actionDialog.open} onOpenChange={(open) => !processing && setActionDialog({ ...actionDialog, open })}>
				<DialogContent>
					<DialogHeader>
						<DialogTitle>
							{actionDialog.type === 'approve' ? 'Approve' : 'Deny'} Submission
						</DialogTitle>
						<DialogDescription>
							{actionDialog.type === 'approve'
								? 'Approving this submission will allow the participant to complete their ticket purchase.'
								: 'Denying this submission will prevent the participant from purchasing a ticket.'}
						</DialogDescription>
					</DialogHeader>

					<div className="space-y-4">
						<div>
							<Label htmlFor="action-notes">
								Notes {actionDialog.type === 'deny' && <span className="text-destructive">*</span>}
							</Label>
							<Textarea
								id="action-notes"
								value={actionNotes}
								onChange={(e) => setActionNotes(e.target.value)}
								placeholder={
									actionDialog.type === 'approve'
										? 'Optional: Add any notes about this approval'
										: 'Required: Please provide a reason for denial'
								}
								rows={3}
							/>
						</div>
					</div>

					<DialogFooter>
						<Button
							variant="outline"
							onClick={() => setActionDialog({ open: false, type: null, submission: null })}
							disabled={processing}
						>
							Cancel
						</Button>
						<Button
							variant={actionDialog.type === 'approve' ? 'default' : 'destructive'}
							onClick={handleAction}
							disabled={processing || (actionDialog.type === 'deny' && !actionNotes.trim())}
						>
							{processing && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
							{actionDialog.type === 'approve' ? 'Approve' : 'Deny'}
						</Button>
					</DialogFooter>
				</DialogContent>
			</Dialog>
		</div>
	);
}
