// ui/src/lib/components/admin/variant-stock-manager.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { toast } from "svelte-sonner";

	import apiClient from "$lib/api";

	import { Button } from "$lib/components/ui/button";
	import { Card } from "$lib/components/ui/card";
	import { Input } from "$lib/components/ui/input";
	import type { Price } from "$lib/schemas/price";

	interface Props {
		productId: string;
	}

	interface VariantResponse {
		variants?: Price[];
	}

	let { productId }: Props = $props();

	let variants = $state<Price[]>([]);
	let quantities = $state<Record<string, string>>({});

	let loading = $state(true);
	let saving = $state(false);
	let errorMessage = $state("");

	const totalStock = $derived(
		Object.values(quantities).reduce(
			(total, value) => total + (Number.parseInt(value, 10) || 0),
			0,
		),
	);

	const dirty = $derived(
		variants.some((variant) => {
			const originalQuantity =
				variant.stock_quantity === undefined
					? ""
					: String(variant.stock_quantity);

			return quantities[variant.id] !== originalQuantity;
		}),
	);

	onMount(() => {
		void loadVariants();
	});

	async function loadVariants() {
		loading = true;
		errorMessage = "";

		try {
			const response = await apiClient.get<VariantResponse>(
				`/admin/products/${productId}/variants`,
			);

			variants = response.variants ?? [];

			quantities = Object.fromEntries(
				variants.map((variant) => [
					variant.id,
					variant.stock_quantity === undefined
						? ""
						: String(variant.stock_quantity),
				]),
			);
		} catch (error) {
			console.error("Failed to load variant stock:", error);
			errorMessage = "Failed to load variant stock levels.";
		} finally {
			loading = false;
		}
	}

	function setQuantity(id: string, value: string) {
		if (value && !/^\d+$/.test(value)) {
			return;
		}

		quantities = {
			...quantities,
			[id]: value,
		};
	}

	function getStockStatus(quantity: string): string {
		const numericQuantity = Number.parseInt(quantity, 10) || 0;

		if (numericQuantity === 0) {
			return "Out of stock";
		}

		if (numericQuantity < 5) {
			return "Low stock";
		}

		return "In stock";
	}

	async function saveChanges() {
		if (!dirty || saving) {
			return;
		}

		saving = true;

		try {
			await apiClient.put(`/admin/products/${productId}/variants/stock`, {
				variants: variants.map((variant) => {
					const quantity = quantities[variant.id] ?? "";

					return {
						id: variant.id,
						stock_quantity:
							quantity === "" ? null : Number(quantity),
					};
				}),
			});

			toast.success("Stock levels updated.");

			await loadVariants();
		} catch (error) {
			console.error("Failed to update stock levels:", error);
			toast.error("Failed to update stock levels.");
		} finally {
			saving = false;
		}
	}
</script>

{#if loading}
	<div class="h-32 animate-pulse rounded-lg bg-muted"></div>
{:else if errorMessage}
	<Card class="p-5">
		<p class="text-sm text-destructive">
			{errorMessage}
		</p>

		<Button
			type="button"
			variant="outline"
			class="mt-4"
			onclick={loadVariants}
		>
			Retry
		</Button>
	</Card>
{:else if variants.length > 0}
	<Card class="space-y-5 p-5">
		<div>
			<h2 class="text-lg font-semibold">Variant stock levels</h2>

			<p class="text-sm text-muted-foreground">
				Inventory is stored in the database for each product variant.
			</p>
		</div>

		<div class="flex items-center justify-between rounded-lg bg-muted p-3">
			<span class="font-medium"> Total stock </span>

			<span class="rounded-full border px-2 py-1 text-sm">
				{totalStock} units
			</span>
		</div>

		<div class="space-y-3">
			{#each variants as variant (variant.id)}
				{@const quantity = quantities[variant.id] ?? ""}

				<div
					class="flex flex-col gap-3 rounded-lg border p-3 md:flex-row md:items-center"
				>
					<div class="min-w-0 flex-1">
						<p class="font-medium">
							{variant.nickname || "Default"}
						</p>

						{#if variant.size || variant.color}
							<p class="text-sm text-muted-foreground">
								{variant.size ? `Size: ${variant.size}` : ""}

								{variant.size && variant.color ? " • " : ""}

								{variant.color ? `Color: ${variant.color}` : ""}
							</p>
						{/if}

						<p class="text-xs text-muted-foreground">
							Price: {(variant.unit_amount / 100).toFixed(2)}
						</p>
					</div>

					<div class="flex items-center gap-2">
						<Input
							type="number"
							min="0"
							value={quantity}
							placeholder="∞"
							class="w-24"
							onchange={(event) => {
								const input =
									event.currentTarget as HTMLInputElement;

								setQuantity(variant.id, input.value);
							}}
						/>

						<span class="rounded-full border px-2 py-1 text-xs">
							{getStockStatus(quantity)}
						</span>
					</div>
				</div>
			{/each}
		</div>

		{#if dirty}
			<p
				class="rounded-lg border border-yellow-300/50 bg-yellow-50 p-3 text-sm dark:bg-yellow-950/20"
			>
				You have unsaved stock changes.
			</p>
		{/if}

		<Button
			type="button"
			class="w-full"
			onclick={saveChanges}
			disabled={!dirty || saving}
		>
			{saving ? "Saving…" : "Save stock levels"}
		</Button>
	</Card>
{/if}

// src/components/admin/variant-stock-manager.tsx
import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card';
import { Input } from '~/components/ui/input';
import { Button } from '~/components/ui/button';
import { Badge } from '~/components/ui/badge';
import { Alert, AlertDescription } from '~/components/ui/alert';
import { apiClient } from '~/lib/api';
import { toast } from 'sonner';
import { Package, Save, AlertCircle } from 'lucide-react';

interface VariantStockManagerProps {
	productId: string;
}

interface VariantPrice {
	id: string;
	nickname: string | null;
	unit_amount: number;
	metadata: {
		variant?: string;
		size?: string;
		color?: string;
		in_stock?: string;
		stock_quantity?: string;
		[key: string]: string | undefined;
	};
}

export function VariantStockManager({ productId }: VariantStockManagerProps) {
	const [prices, setPrices] = useState<VariantPrice[]>([]);
	const [stockQuantities, setStockQuantities] = useState<Record<string, string>>({});
	const [isLoading, setIsLoading] = useState(true);
	const [isSaving, setIsSaving] = useState(false);
	const [hasChanges, setHasChanges] = useState(false);

	// Fetch existing prices/variants
	useEffect(() => {
		const fetchPrices = async () => {
			try {
				const response = await apiClient.get(`/admin/product-prices/${productId}`);
				const priceData = response.data.prices || [];
				setPrices(priceData);

				// Initialize stock quantities from metadata
				const initialStock: Record<string, string> = {};
				priceData.forEach((price: VariantPrice) => {
					initialStock[price.id] = price.metadata.stock_quantity || '';
				});
				setStockQuantities(initialStock);
			} catch (error) {
				console.error('Failed to fetch variant prices:', error);
				toast.error('Failed to load variant stock levels');
			} finally {
				setIsLoading(false);
			}
		};

		fetchPrices();
	}, [productId]);

	// Handle stock quantity change
	const handleStockChange = (priceId: string, value: string) => {
		// Only allow numbers
		if (value && !/^\d+$/.test(value)) return;

		setStockQuantities(prev => ({
			...prev,
			[priceId]: value
		}));
		setHasChanges(true);
	};

	// Save all changes
	const saveChanges = async () => {
		setIsSaving(true);
		try {
			// Update each price's metadata with new stock quantity
			const updatePromises = prices.map(async (price) => {
				const newQuantity = stockQuantities[price.id];
				const currentQuantity = price.metadata.stock_quantity || '';

				// Only update if changed
				if (newQuantity !== currentQuantity) {
					await apiClient.put(`/admin/update-price-metadata/${price.id}`, {
						metadata: {
							...price.metadata,
							stock_quantity: newQuantity,
							in_stock: newQuantity === '0' ? 'false' : 'true'
						}
					});
				}
			});

			await Promise.all(updatePromises);
			toast.success('Stock levels updated successfully');
			setHasChanges(false);

			// Refresh prices to get updated metadata
			const response = await apiClient.get(`/admin/product-prices/${productId}`);
			setPrices(response.data.prices || []);
		} catch (error) {
			console.error('Failed to update stock levels:', error);
			toast.error('Failed to update stock levels');
		} finally {
			setIsSaving(false);
		}
	};

	if (isLoading) {
		return <div className="animate-pulse bg-muted h-32 rounded-lg" />;
	}

	if (prices.length === 0) {
		return null;
	}

	// Calculate total stock
	const totalStock = Object.values(stockQuantities).reduce((sum, qty) => {
		const num = parseInt(qty) || 0;
		return sum + num;
	}, 0);

	return (
		<Card>
			<CardHeader>
				<CardTitle className="flex items-center gap-2">
					<Package className="h-5 w-5" />
					Variant Stock Levels
				</CardTitle>
			</CardHeader>
			<CardContent>
				<div className="space-y-4">
					<div className="flex items-center justify-between p-3 bg-muted rounded-lg">
						<span className="font-medium">Total Stock Across All Variants:</span>
						<Badge variant={totalStock > 0 ? "default" : "destructive"}>
							{totalStock} units
						</Badge>
					</div>

					<div className="space-y-2">
						{prices.map((price) => {
							const quantity = stockQuantities[price.id] || '';
							const numQuantity = parseInt(quantity) || 0;

							return (
								<div key={price.id} className="flex items-center gap-4 p-3 border rounded-lg">
									<div className="flex-1">
										<p className="font-medium">
											{price.metadata.variant || price.nickname || 'Default'}
										</p>
										{(price.metadata.size || price.metadata.color) && (
											<p className="text-sm text-muted-foreground">
												{price.metadata.size && `Size: ${price.metadata.size}`}
												{price.metadata.size && price.metadata.color && ' • '}
												{price.metadata.color && `Color: ${price.metadata.color}`}
											</p>
										)}
									</div>

									<div className="flex items-center gap-2">
										<Input
											type="number"
											min="0"
											value={quantity}
											onChange={(e) => handleStockChange(price.id, e.target.value)}
											className="w-24"
											placeholder="∞"
										/>
										<Badge
											variant={numQuantity === 0 ? "destructive" : numQuantity < 5 ? "secondary" : "default"}
										>
											{numQuantity === 0 ? 'Out of Stock' : numQuantity < 5 ? 'Low Stock' : 'In Stock'}
										</Badge>
									</div>
								</div>
							);
						})}
					</div>

					{hasChanges && (
						<Alert>
							<AlertCircle className="h-4 w-4" />
							<AlertDescription>
								You have unsaved changes to stock levels
							</AlertDescription>
						</Alert>
					)}

					<Button
						onClick={saveChanges}
						disabled={!hasChanges || isSaving}
						className="w-full"
					>
						<Save className="h-4 w-4 mr-2" />
						{isSaving ? 'Saving...' : 'Save Stock Levels'}
					</Button>
				</div>
			</CardContent>
		</Card>
	);
}
