// src/components/footer.tsx
import { Facebook, Instagram, Mail, Phone, Youtube } from 'lucide-react';
import { Image } from './ui/image';

const socialLinks = [
	{
		name: 'Facebook',
		url: '#',
		icon: '/facebook.svg',
	},
	{
		name: 'Instagram',
		url: '#',
		icon: '/instagram.svg',
	},
	{
		name: 'YouTube',
		url: '#',
		icon: '/youtube.svg',
	},
];

export function Footer() {
	return (
		<footer className="bg-muted py-12">
			<div className="px-4 md:px-6">
				<div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-4">
					<div>
						<h3 className="text-lg font-bold">Euro Haus</h3>
						<p className="mt-2 text-sm text-muted-foreground">Building a community around car enthusiasm since 2023.</p>
						<div className="mt-4 flex space-x-3">
							<a href="https://instagram.com/theeurohaus" className="text-muted-foreground hover:text-primary">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinejoin="round" stroke-linejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-instagram"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 8a4 4 0 0 1 4 -4h8a4 4 0 0 1 4 4v8a4 4 0 0 1 -4 4h-8a4 4 0 0 1 -4 -4z" /><path d="M9 12a3 3 0 1 0 6 0a3 3 0 0 0 -6 0" /><path d="M16.5 7.5v.01" /></svg>
								<span className="sr-only">Instagram</span>
							</a>
							<a href="https://facebook.com" className="text-muted-foreground hover:text-primary">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinejoin="round" stroke-linejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-facebook"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M7 10v4h3v7h4v-7h3l1 -4h-4v-2a1 1 0 0 1 1 -1h3v-4h-3a5 5 0 0 0 -5 5v2h-3" /></svg>
								<span className="sr-only">Facebook</span>
							</a>
							<a href="https://youtube.com/@TheEuroHaus" className="text-muted-foreground hover:text-primary">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinejoin="round" stroke-linejoin="round" className="icon icon-tabler icons-tabler-outline icon-tabler-brand-youtube"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M2 8a4 4 0 0 1 4 -4h12a4 4 0 0 1 4 4v8a4 4 0 0 1 -4 4h-12a4 4 0 0 1 -4 -4v-8z" /><path d="M10 9l5 3l-5 3z" /></svg>
								<span className="sr-only">YouTube</span>
							</a>
						</div>
					</div>
					<div>
						<h3 className="text-lg font-bold">Shop</h3>
						<ul className="mt-2 space-y-2 text-sm">
							<li>
								<a href="/catalog" className="text-muted-foreground hover:text-foreground">
									Apparel
								</a>
							</li>
							{/*<li>
								<a href="/shop/accessories" className="text-muted-foreground hover:text-foreground">
									Accessories
								</a>
							</li>*/}
							<li>
								<a href="/events" className="text-muted-foreground hover:text-foreground">
									Event Tickets
								</a>
							</li>
							{/*<li>
								<a href="/shop/gift-cards" className="text-muted-foreground hover:text-foreground">
									Gift Cards
								</a>
							</li>*/}
						</ul>
					</div>
					<div>
						<h3 className="text-lg font-bold">Community</h3>
						<ul className="mt-2 space-y-2 text-sm">
							<li>
								<a href="/events" className="text-muted-foreground hover:text-foreground">
									Events
								</a>
							</li>
							{/*<li>
								<a href="/community/forum" className="text-muted-foreground hover:text-foreground">
									Forum
								</a>
							</li>*/}
							<li>
								<a href="/gallery" className="text-muted-foreground hover:text-foreground">
									Car Gallery
								</a>
							</li>
							{/*<li>
								<a href="/videos" className="text-muted-foreground hover:text-foreground">
									Videos
								</a>
							</li>*/}
						</ul>
					</div>
					<div>
						<h3 className="text-lg font-bold">Contact</h3>
						<ul className="mt-2 space-y-2 text-sm">
							<li className="flex items-center">
								<Mail className="mr-2 h-4 w-4 text-muted-foreground" />
								<a href="mailto:info@theeurohaus.com" className="text-muted-foreground hover:text-foreground">
									info@theeurohaus.com
								</a>
							</li>
						</ul>
					</div>
				</div>
				<div className="mt-12 border-t pt-6">
					<div className="flex flex-col items-center justify-between gap-4 md:flex-row">
						<p className="text-sm text-muted-foreground">
							© {new Date().getFullYear()} Euro Haus. All rights reserved.
						</p>
						<ul className="flex space-x-4 text-sm">
							<li>
								<a href="/terms" className="text-muted-foreground hover:text-foreground">
									Terms
								</a>
							</li>
							<li>
								<a href="/privacy" className="text-muted-foreground hover:text-foreground">
									Privacy
								</a>
							</li>
							<li>
								<a href="/cookies" className="text-muted-foreground hover:text-foreground">
									Cookies
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<span className='text-sm text-muted-foreground'>
				Designed & Developed by <a href='https://ceokoroji.dev' className='text-muted-foreground hover:text-foreground underline'>Chukwuma Okoroji</a>
			</span>
		</footer>
	);
}

// ui/src/lib/components/footer.svelte
<script lang="ts">
	import { Mail } from "@lucide/svelte/icons";
	import Facebook from "$lib/assets/facebook.svg";
	import Youtube from "$lib/assets/youtube.svg";
	import Instagram from "$lib/assets/instagram.svg";
	import { buttonVariants } from "./ui/button";

	const socialLinks = [
		{
			name: "Instagram",
			url: "https://instagram.com/theeurohaus",
			icon: Instagram,
		},
		{
			name: "Facebook",
			url: "https://facebook.com",
			icon: Facebook,
		},
		{
			name: "YouTube",
			url: "https://youtube.com/@TheEuroHaus",
			icon: Youtube,
		},
	] as const;

	const shopLinks = [
		{ label: "Apparel", href: "/catalog" },
		{ label: "Event Tickets", href: "/events" },
	] as const;

	const communityLinks = [
		{ label: "Events", href: "/events" },
		{ label: "Car Gallery", href: "/gallery" },
	] as const;

	const legalLinks = [
		{ label: "Terms", href: "/terms" },
		{ label: "Privacy", href: "/privacy" },
		{ label: "Cookies", href: "/cookies" },
	] as const;

	const currentYear = new Date().getFullYear();
</script>

<footer class="border-t bg-background">
	<div class="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
		<div class="grid gap-8 md:grid-cols-2 lg:grid-cols-4">
			<div>
				<h2 class="text-lg font-semibold">Euro Haus</h2>
				<p class="mt-2 text-sm leading-6">
					Building a community around car enthusiasm since 2023.
				</p>

				<div class="mt-4 flex items-center gap-3">
					{#each socialLinks as social (social.name)}
						{@const Icon = social.icon}
						<a
							href={social.url}
							target="_blank"
							rel="noreferrer"
							class={buttonVariants({
								variant: "circle",
								size: "icon-sm",
							})}
							aria-label={social.name}
						>
							<img src={Icon} alt={social.name} class="size-5" />
						</a>
					{/each}
				</div>
			</div>

			<div>
				<h3 class="text-lg font-semibold">Shop</h3>
				<ul class="mt-3 space-y-2 text-sm">
					{#each shopLinks as link (link.href)}
						<li>
							<a
								href={link.href}
								data-sveltekit-preload-data="hover"
								class="transition hover:text-primary"
							>
								{link.label}
							</a>
						</li>
					{/each}
				</ul>
			</div>

			<div>
				<h3 class="text-lg font-semibold">Community</h3>
				<ul class="mt-3 space-y-2 text-sm">
					{#each communityLinks as link (link.href)}
						<li>
							<a
								href={link.href}
								data-sveltekit-preload-data="hover"
								class="transition hover:text-primary"
							>
								{link.label}
							</a>
						</li>
					{/each}
				</ul>
			</div>

			<div>
				<h3 class="text-lg font-semibold">Contact</h3>
				<ul class="mt-3 space-y-2 text-sm">
					<li class="flex items-start gap-2">
						<Mail class="mt-0.5 size-4 shrink-0" />
						<a
							href="mailto:info@theeurohaus.com"
							class="transition hover:text-primary"
						>
							info@theeurohaus.com
						</a>
					</li>
				</ul>
			</div>
		</div>

		<div class="mt-12 border-t border-border pt-6">
			<div
				class="flex flex-col items-center justify-between gap-4 md:flex-row"
			>
				<p class="text-sm">
					© {currentYear} Euro Haus. All rights reserved.
				</p>

				<ul
					class="flex flex-wrap items-center justify-center gap-4 text-sm"
				>
					{#each legalLinks as link (link.href)}
						<li>
							<a
								href={link.href}
								data-sveltekit-preload-data="hover"
								class="transition hover:text-primary"
							>
								{link.label}
							</a>
						</li>
					{/each}
				</ul>
			</div>
		</div>

		<address class="mt-6 text-center text-sm not-italic">
			Designed &amp; Developed by
			<a
				href="https://ceokoroji.dev"
				target="_blank"
				rel="noreferrer"
				class="underline transition hover:text-primary"
			>
				Chukwuma Okoroji
			</a>
		</address>
	</div>
</footer>
