// src/components/vehicle-submission-form.tsx
import React, { useState } from 'react';
import { useForm, useFieldArray } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { Upload, X, Car, AlertCircle, Ticket, DollarSign, Plus, Trash2 } from 'lucide-react';
import { Button } from '~/components/ui/button';
import { Input } from '~/components/ui/input';
import { Textarea } from '~/components/ui/textarea';
import { Label } from '~/components/ui/label';
import {
	Form,
	FormControl,
	FormDescription,
	FormField,
	FormItem,
	FormLabel,
	FormMessage,
} from '~/components/ui/form';
import { Alert, AlertDescription } from '~/components/ui/alert';
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card';
import { submissionService } from '~/lib/services/submission-service';
import type { SubmissionWithFiles } from '~/lib/services/submission-service';

const formSchema = z.object({
	participantName: z.string().min(2, 'Name must be at least 2 characters'),
	participantEmail: z.string().email('Invalid email address'),
	participantPhone: z.string().optional(),
	vehicleYear: z.string().regex(/^\d{4}$/, 'Year must be 4 digits'),
	vehicleMake: z.string().min(2, 'Make is required'),
	vehicleModel: z.string().min(2, 'Model is required'),
	vehicleDescription: z.string().optional(),
	vehicleModifications: z.array(z.object({ value: z.string() })).optional(),
});

type FormData = z.infer<typeof formSchema>;

interface VehicleSubmissionFormProps {
	eventId: string;
	eventSlug: string;
	eventName: string;
	ticketTier?: string;
	ticketPrice?: number;
	ticketQuantity?: number;
	onSuccess: (submissionId: string) => void;
	onCancel: () => void;
}

export function VehicleSubmissionForm({
	eventId,
	eventSlug,
	eventName,
	ticketTier,
	ticketPrice,
	ticketQuantity,
	onSuccess,
	onCancel,
}: VehicleSubmissionFormProps) {
	const [images, setImages] = useState<File[]>([]);
	const [imagePreviews, setImagePreviews] = useState<string[]>([]);
	const [uploading, setUploading] = useState(false);
	const [error, setError] = useState<string | null>(null);

	const form = useForm<FormData>({
		resolver: zodResolver(formSchema),
		defaultValues: {
			participantName: '',
			participantEmail: '',
			participantPhone: '',
			vehicleYear: '',
			vehicleMake: '',
			vehicleModel: '',
			vehicleDescription: '',
			vehicleModifications: []
		},
	});

	const {
		fields: vehicleModifications,
		append: appendModification,
		remove: removeModification,
		update: updateModification
	} = useFieldArray({
		control: form.control,
		name: "vehicleModifications"
	})

	const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		const files = Array.from(e.target.files || []);

		// Validate images
		const validation = submissionService.validateImages(files);
		if (!validation.valid) {
			setError(validation.error!);
			return;
		}

		// Limit to 5 images
		if (images.length + files.length > 5) {
			setError('Maximum 5 images allowed');
			return;
		}

		setError(null);

		// Add new images
		const newImages = [...images, ...files];
		setImages(newImages);

		// Create previews
		files.forEach((file) => {
			const reader = new FileReader();
			reader.onloadend = () => {
				setImagePreviews((prev) => [...prev, reader.result as string]);
			};
			reader.readAsDataURL(file);
		});
	};

	const removeImage = (index: number) => {
		setImages((prev) => prev.filter((_, i) => i !== index));
		setImagePreviews((prev) => prev.filter((_, i) => i !== index));
	};

	const onSubmit = async (data: FormData) => {
		if (images.length === 0) {
			setError('Please upload at least one image of your vehicle');
			return;
		}

		setUploading(true);
		setError(null);

		// Transform the modifications from an object array to string array and filter empty values
		const vehicleModifications = data.vehicleModifications
			?.filter(mod => mod.value.trim() !== '')
			.map(mod => mod.value.trim());


		try {
			const submissionData: SubmissionWithFiles = {
				...data,
				eventId,
				eventSlug,
				images,
				ticketTier,
				ticketPrice,
				ticketQuantity,
				vehicleModifications
			};

			const submission = await submissionService.createSubmission(submissionData);
			onSuccess(submission.id);
		} catch (err) {
			setError(err instanceof Error ? err.message : 'Failed to submit vehicle information');
		} finally {
			setUploading(false);
		}
	};

	return (
		<div className="space-y-6">
			<div className="text-center">
				<Car className="mx-auto h-12 w-12 text-primary mb-4" />
				<h2 className="text-2xl font-bold">Vehicle Submission for {eventName}</h2>
				<p className="text-muted-foreground mt-2">
					Please provide details about the vehicle you wish to enter in this event.
				</p>
			</div>

			{/* Ticket Information */}
			{ticketTier && (
				<Card className="bg-primary/5 border-primary/20">
					<CardHeader className="pb-3">
						<CardTitle className="text-lg flex items-center gap-2">
							<Ticket className="w-5 h-5" />
							Selected Ticket
						</CardTitle>
					</CardHeader>
					<CardContent>
						<div className="flex flex-wrap gap-4 items-center">
							<div>
								<p className="text-sm text-muted-foreground">Tier</p>
								<p className="font-semibold">{ticketTier}</p>
							</div>
							{ticketPrice && (
								<div>
									<p className="text-sm text-muted-foreground">Price</p>
									<p className="font-semibold flex items-center">
										<DollarSign className="w-4 h-4" />
										{ticketPrice.toFixed(2)}
									</p>
								</div>
							)}
							{ticketQuantity && (
								<div>
									<p className="text-sm text-muted-foreground">Quantity</p>
									<p className="font-semibold">{ticketQuantity} ticket{ticketQuantity > 1 ? 's' : ''}</p>
								</div>
							)}
							{ticketPrice && ticketQuantity && (
								<div className="ml-auto">
									<p className="text-sm text-muted-foreground">Total</p>
									<p className="font-semibold flex items-center">
										<DollarSign className="w-4 h-4" />
										{(ticketPrice * ticketQuantity).toFixed(2)}
									</p>
								</div>
							)}
						</div>
					</CardContent>
				</Card>
			)}

			{error && (
				<Alert variant="destructive">
					<AlertCircle className="h-4 w-4" />
					<AlertDescription>{error}</AlertDescription>
				</Alert>
			)}

			<Form {...form}>
				<form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
					{/* Personal Information */}
					<div className="space-y-4">
						<h3 className="text-lg font-semibold">Your Information</h3>

						<FormField
							control={form.control}
							name="participantName"
							render={({ field }) => (
								<FormItem>
									<FormLabel>Full Name</FormLabel>
									<FormControl>
										<Input {...field} placeholder="John Doe" />
									</FormControl>
									<FormMessage />
								</FormItem>
							)}
						/>

						<div className="grid grid-cols-1 md:grid-cols-2 gap-4">
							<FormField
								control={form.control}
								name="participantEmail"
								render={({ field }) => (
									<FormItem>
										<FormLabel>Email</FormLabel>
										<FormControl>
											<Input {...field} type="email" placeholder="john@example.com" />
										</FormControl>
										<FormMessage />
									</FormItem>
								)}
							/>

							<FormField
								control={form.control}
								name="participantPhone"
								render={({ field }) => (
									<FormItem>
										<FormLabel>Phone (Optional)</FormLabel>
										<FormControl>
											<Input {...field} type="tel" placeholder="+1 (555) 123-4567" />
										</FormControl>
										<FormMessage />
									</FormItem>
								)}
							/>
						</div>
					</div>

					{/* Vehicle Information */}
					<div className="space-y-4">
						<h3 className="text-lg font-semibold">Vehicle Information</h3>

						<div className="grid grid-cols-1 md:grid-cols-3 gap-4">
							<FormField
								control={form.control}
								name="vehicleYear"
								render={({ field }) => (
									<FormItem>
										<FormLabel>Year</FormLabel>
										<FormControl>
											<Input {...field} placeholder="2023" maxLength={4} />
										</FormControl>
										<FormMessage />
									</FormItem>
								)}
							/>

							<FormField
								control={form.control}
								name="vehicleMake"
								render={({ field }) => (
									<FormItem>
										<FormLabel>Make</FormLabel>
										<FormControl>
											<Input {...field} placeholder="Porsche" />
										</FormControl>
										<FormMessage />
									</FormItem>
								)}
							/>

							<FormField
								control={form.control}
								name="vehicleModel"
								render={({ field }) => (
									<FormItem>
										<FormLabel>Model</FormLabel>
										<FormControl>
											<Input {...field} placeholder="911 GT3" />
										</FormControl>
										<FormMessage />
									</FormItem>
								)}
							/>
						</div>

						<FormField
							control={form.control}
							name="vehicleDescription"
							render={({ field }) => (
								<FormItem>
									<FormLabel>Vehicle Description (Optional)</FormLabel>
									<FormControl>
										<Textarea
											{...field}
											placeholder="Tell us about your vehicle's history, special features, etc."
											rows={3}
										/>
									</FormControl>
									<FormDescription>
										Share what makes your vehicle special
									</FormDescription>
									<FormMessage />
								</FormItem>
							)}
						/>

						{/* Vehicle Modifications */}
						<div className='bg-muted/50 p-4 rounded-md'>
							<div className='flex justify-between items-center mb-3'>
								<h3 className='text-lg font-medium'>Vehicle Modifications</h3>
								<Button
									type='button'
									size='sm'
									onClick={() => appendModification({ value: '' })}
								>
									<Plus className="h-4 w-4 mr-1" /> Add Modification
								</Button>
							</div>

							{vehicleModifications.length === 0 ? (
								<div className="text-center py-4 text-muted-foreground">
									No tags added yet. Add tags to help categorize your event.
								</div>
							) : (
								<div className="space-y-2">
									{vehicleModifications.map((field, index) => (
										<div key={field.id} className="flex items-end gap-2">
											<FormField
												control={form.control}
												name={`vehicleModifications.${index}.value`}
												render={({ field }) => (
													<FormItem className="flex-1">
														<FormControl>
															<Input {...field} placeholder="e.g., Turbocharged, Modified Suspension" />
														</FormControl>
														<FormMessage />
													</FormItem>
												)}
											/>
											<Button
												type="button"
												variant="ghost"
												size="icon"
												onClick={() => removeModification(index)}
											>
												<Trash2 className="h-4 w-4" />
											</Button>
										</div>
									))}
								</div>
							)}
						</div>
					</div>

					{/* Image Upload */}
					<div className="space-y-4">
						<h3 className="text-lg font-semibold">Vehicle Images</h3>
						<p className="text-sm text-muted-foreground">
							Upload up to 5 images of your vehicle. Include exterior, interior, and engine bay shots if possible.
						</p>

						<div className="space-y-4">
							<Label htmlFor="image-upload" className="cursor-pointer">
								<div className="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center hover:border-gray-400 transition-colors">
									<Upload className="mx-auto h-12 w-12 text-gray-400" />
									<p className="mt-2 text-sm text-gray-600">
										Click to upload images or drag and drop
									</p>
									<p className="text-xs text-gray-500">
										JPEG, PNG or WebP, max 10MB each
									</p>
								</div>
								<input
									id="image-upload"
									type="file"
									multiple
									accept="image/jpeg,image/png,image/webp"
									onChange={handleImageChange}
									className="hidden"
									disabled={uploading}
								/>
							</Label>

							{/* Image Previews */}
							{imagePreviews.length > 0 && (
								<div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
									{imagePreviews.map((preview, index) => (
										<div key={index} className="relative group">
											<img
												src={preview}
												alt={`Vehicle ${index + 1}`}
												className="w-full h-24 object-cover rounded-lg"
											/>
											<button
												type="button"
												onClick={() => removeImage(index)}
												className="absolute top-1 right-1 bg-red-500 text-white rounded-full p-1 opacity-0 group-hover:opacity-100 transition-opacity"
											>
												<X className="h-4 w-4" />
											</button>
										</div>
									))}
								</div>
							)}
						</div>
					</div>

					<div className="flex gap-4">
						<Button
							type="button"
							variant="outline"
							onClick={onCancel}
							disabled={uploading}
						>
							Cancel
						</Button>
						<Button type="submit" disabled={uploading || images.length === 0}>
							{uploading ? 'Submitting...' : 'Submit for Review'}
						</Button>
					</div>
				</form>
			</Form>
		</div>
	);
}

// ui/src/lib/components/vehicle-submission-form.svelte
<script lang="ts">
	import { fade, fly } from "svelte/transition";
	import { toast } from "svelte-sonner";

	import apiClient from "$lib/api";
	import type { VehicleSubmission } from "$lib/schemas/event";

	interface Props {
		eventId: string;
		eventSlug: string;
		priceId: string;
		ticketTier: string;
		ticketPrice: number;
		ticketQuantity: number;
		onsucceed: (submission: VehicleSubmission) => Promise<void>;
		oncancel: () => void;
	}

	interface VehicleDetails {
		participantName: string;
		participantEmail: string;
		participantPhone: string;
		vehicleYear: string;
		vehicleMake: string;
		vehicleModel: string;
		vehicleDescription: string;
	}

	interface UploadProgress {
		loaded: number;
		total: number;
		percent: number;
	}

	let {
		eventId,
		eventSlug,
		priceId,
		ticketTier,
		ticketPrice,
		ticketQuantity,
		onsucceed,
		oncancel,
	}: Props = $props();

	let step = $state<1 | 2>(1);

	let details = $state<VehicleDetails>({
		participantName: "",
		participantEmail: "",
		participantPhone: "",
		vehicleYear: "",
		vehicleMake: "",
		vehicleModel: "",
		vehicleDescription: "",
	});

	let modifications = $state<string[]>([]);
	let files = $state<File[]>([]);
	let previews = $state<string[]>([]);
	let uploadProgress = $state(0);
	let submitting = $state(false);
	let errorMessage = $state("");

	let formElement: HTMLFormElement;

	const total = $derived(ticketPrice * ticketQuantity);

	function addModification() {
		modifications = [...modifications, ""];
	}

	function removeModification(index: number) {
		modifications = modifications.filter(
			(_, itemIndex) => itemIndex !== index,
		);
	}

	function addImages(event: Event) {
		const input = event.currentTarget as HTMLInputElement;
		const selected = Array.from(input.files ?? []);

		const valid = selected.filter(
			(file) =>
				["image/jpeg", "image/png", "image/webp"].includes(file.type) &&
				file.size <= 10 * 1024 * 1024,
		);

		if (valid.length !== selected.length) {
			errorMessage = "Use JPEG, PNG, or WebP files up to 10MB each.";
		}

		if (files.length + valid.length > 5) {
			errorMessage = "You can upload a maximum of five images.";
		}

		const nextFiles = [...files, ...valid].slice(0, 5);

		files = nextFiles;
		previews = nextFiles.map((file) => URL.createObjectURL(file));

		// Allows the same file to be selected again after removing it.
		input.value = "";
	}

	function removeImage(index: number) {
		files = files.filter((_, fileIndex) => fileIndex !== index);
		previews = previews.filter((_, fileIndex) => fileIndex !== index);
	}

	function continueToImages() {
		errorMessage = "";

		if (!formElement.reportValidity()) {
			return;
		}

		step = 2;
	}

	async function submit(event: SubmitEvent) {
		event.preventDefault();
		errorMessage = "";

		if (step === 1) {
			continueToImages();
			return;
		}

		if (files.length === 0) {
			errorMessage =
				"Add at least one image of your vehicle to continue.";
			return;
		}

		if (!priceId) {
			errorMessage = "The selected ticket price is unavailable.";
			return;
		}

		submitting = true;
		uploadProgress = 0;

		const body = new FormData();

		// These names match internal/handlers/submission.go.
		body.set("event_id", eventId);
		body.set("event_slug", eventSlug);
		body.set("participant_name", details.participantName);
		body.set("participant_email", details.participantEmail);
		body.set("participant_phone", details.participantPhone);
		body.set("vehicle_year", details.vehicleYear);
		body.set("vehicle_make", details.vehicleMake);
		body.set("vehicle_model", details.vehicleModel);
		body.set("vehicle_description", details.vehicleDescription);
		body.set(
			"vehicle_modifications",
			modifications
				.filter((modification) => modification.trim())
				.join("\n"),
		);

		// This must be the Stripe Price ID, not the display name.
		body.set("price_id", priceId);

		for (const file of files) {
			body.append("images", file);
		}

		try {
			const submission = await apiClient.upload<VehicleSubmission>(
				"/submissions",
				body,
				({ percent }: UploadProgress) => {
					uploadProgress = percent;
				},
			);

			await onsucceed(submission);

			toast.success(
				"Vehicle submitted. Continue to checkout when ready.",
			);
		} catch (error) {
			console.error("Vehicle submission failed:", error);

			errorMessage =
				error instanceof Error
					? error.message
					: "Unable to submit your vehicle right now.";
		} finally {
			submitting = false;
		}
	}
</script>

<section
	class="submission-shell"
	aria-labelledby="submission-title"
	in:fly={{ y: 18, duration: 300 }}
>
	<div class="submission-header">
		<div>
			<p class="eyebrow">Vehicle entry</p>

			<h2 id="submission-title">Show us your build.</h2>

			<p class="submission-intro">
				A few details help our team understand what you are bringing to
				the event.
			</p>
		</div>

		<button
			type="button"
			class="close-button"
			onclick={oncancel}
			aria-label="Close vehicle submission"
		>
			×
		</button>
	</div>

	<div class="ticket-summary">
		<div>
			<span>Ticket</span>
			<strong>{ticketTier || "Vehicle entry"}</strong>
		</div>

		<div>
			<span>Quantity</span>
			<strong>{ticketQuantity}</strong>
		</div>

		<div>
			<span>Total</span>
			<strong>${total.toFixed(2)}</strong>
		</div>
	</div>

	<div class="progress" aria-label={`Step ${step} of 2`}>
		<div class="progress-track">
			<span style={`width: ${step === 1 ? 50 : 100}%`}></span>
		</div>

		<div class="progress-labels">
			<span class:current={step === 1}>01 · Your details</span>
			<span class:current={step === 2}>
				02 · Photos and modifications
			</span>
		</div>
	</div>

	{#if errorMessage}
		<p class="error-message" role="alert">
			{errorMessage}
		</p>
	{/if}

	<form bind:this={formElement} onsubmit={submit}>
		{#if step === 1}
			<div class="form-grid" in:fade={{ duration: 180 }}>
				<label class="full">
					Full name
					<input
						bind:value={details.participantName}
						required
						minlength="2"
						placeholder="Alex Morgan"
					/>
				</label>

				<label>
					Email
					<input
						bind:value={details.participantEmail}
						required
						type="email"
						placeholder="alex@example.com"
					/>
				</label>

				<label>
					Phone <span>(optional)</span>
					<input
						bind:value={details.participantPhone}
						type="tel"
						placeholder="(555) 123-4567"
					/>
				</label>

				<label>
					Year
					<input
						bind:value={details.vehicleYear}
						required
						type="number"
						pattern="[0-9]{4}"
						maxlength={4}
						inputmode="numeric"
						placeholder="2024"
					/>
				</label>

				<label>
					Make
					<input
						bind:value={details.vehicleMake}
						required
						minlength="2"
						placeholder="Porsche"
					/>
				</label>

				<label>
					Model
					<input
						bind:value={details.vehicleModel}
						required
						minlength="2"
						placeholder="911 GT3"
					/>
				</label>

				<label class="full">
					Tell us about the car <span>(optional)</span>
					<textarea
						bind:value={details.vehicleDescription}
						rows="4"
						placeholder="What makes this car special?"></textarea>
				</label>
			</div>

			<div class="form-actions">
				<button type="button" class="secondary" onclick={oncancel}>
					Cancel
				</button>

				<button type="submit" class="primary">
					Continue
					<span aria-hidden="true">→</span>
				</button>
			</div>
		{:else}
			<div class="photo-step" in:fade={{ duration: 180 }}>
				<div class="upload-copy">
					<p class="eyebrow">01 / Photos</p>

					<h3>Let the details speak.</h3>

					<p>
						Upload up to five clear photos. Your first photo will be
						used as the cover image.
					</p>
				</div>

				<label class="dropzone">
					<input
						type="file"
						accept="image/jpeg,image/png,image/webp"
						multiple
						onchange={addImages}
						disabled={submitting}
					/>

					<span class="upload-icon">＋</span>
					<strong>Choose vehicle photos</strong>
					<small>JPEG, PNG, or WebP · 10MB max each</small>
				</label>

				{#if previews.length > 0}
					<div class="preview-grid">
						{#each previews as preview, index (preview)}
							<figure>
								<img
									src={preview}
									alt={`Vehicle preview ${index + 1}`}
								/>

								<button
									type="button"
									onclick={() => removeImage(index)}
									aria-label={`Remove photo ${index + 1}`}
								>
									×
								</button>

								{#if index === 0}
									<figcaption>Cover</figcaption>
								{/if}
							</figure>
						{/each}
					</div>
				{/if}

				<div class="modifications">
					<div class="section-row">
						<div>
							<p class="eyebrow">02 / Details</p>
							<h3>What have you changed?</h3>
						</div>

						<button
							type="button"
							class="secondary small"
							onclick={addModification}
						>
							＋ Add modification
						</button>
					</div>

					{#if modifications.length === 0}
						<p class="empty-state">No modifications added yet.</p>
					{:else}
						{#each modifications as _, index (index)}
							<div class="modification-row">
								<input
									bind:value={modifications[index]}
									placeholder="e.g. KW suspension, forged wheels"
								/>

								<button
									type="button"
									onclick={() => removeModification(index)}
									aria-label={`Remove modification ${index + 1}`}
								>
									×
								</button>
							</div>
						{/each}
					{/if}
				</div>

				<div class="form-actions">
					<button
						type="button"
						class="secondary"
						onclick={() => (step = 1)}
						disabled={submitting}
					>
						← Back
					</button>

					<button
						type="submit"
						class="primary"
						disabled={submitting || files.length === 0}
					>
						{#if submitting}
							Uploading {uploadProgress}%…
						{:else}
							Submit and continue
						{/if}
					</button>
				</div>
			</div>
		{/if}
	</form>
</section>

<style>
	.submission-shell {
		max-width: 760px;
		margin: 0 auto;
		padding: clamp(24px, 5vw, 54px);
		background: var(--background);
		color: var(--foreground);
		box-shadow: 0 24px 80px
			color-mix(in srgb, var(--foreground) 20%, transparent);
	}

	.submission-header,
	.section-row,
	.form-actions,
	.progress-labels {
		display: flex;
		align-items: flex-start;
		justify-content: space-between;
		gap: 20px;
	}

	.submission-header h2 {
		margin: 8px 0 12px;
		font-family: var(--font-display);
		font-size: clamp(52px, 8vw, 92px);
		letter-spacing: -0.055em;
		line-height: 0.8;
		text-transform: uppercase;
	}

	.submission-intro {
		max-width: 460px;
		margin: 0;
		color: var(--muted);
	}

	.close-button,
	.modification-row button,
	.preview-grid figure button {
		border: 0;
		background: transparent;
		color: inherit;
		cursor: pointer;
		font-size: 24px;
	}

	.ticket-summary {
		display: grid;
		grid-template-columns: 1fr 1fr 1fr;
		gap: 1px;
		margin: 36px 0;
		background: var(--border);
		border: 1px solid var(--border);
	}

	.ticket-summary div {
		display: grid;
		gap: 6px;
		padding: 16px;
		background: var(--background);
	}

	.ticket-summary span,
	label span {
		color: var(--muted);
		font-size: 11px;
	}

	.ticket-summary strong {
		font-size: 15px;
	}

	.progress {
		margin-bottom: 34px;
	}

	.progress-track {
		height: 3px;
		background: var(--border);
	}

	.progress-track span {
		display: block;
		height: 100%;
		background: var(--primary);
		transition: width 0.3s ease;
	}

	.progress-labels {
		margin-top: 10px;
		color: var(--muted);
		font-size: 10px;
		letter-spacing: 0.08em;
		text-transform: uppercase;
	}

	.progress-labels .current {
		color: var(--foreground);
	}

	.error-message {
		padding: 12px 14px;
		border-left: 3px solid var(--destructive);
		color: var(--destructive);
		background: color-mix(in srgb, var(--destructive) 8%, transparent);
	}

	.form-grid {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 18px;
	}

	label {
		display: grid;
		gap: 8px;
		color: var(--foreground);
		font-size: 12px;
	}

	label.full {
		grid-column: 1 / -1;
	}

	input,
	textarea {
		width: 100%;
		border: 1px solid var(--border);
		border-radius: 0;
		padding: 13px 14px;
		background: transparent;
		color: inherit;
		font: inherit;
	}

	input:focus,
	textarea:focus {
		outline: 2px solid var(--primary);
		outline-offset: 1px;
	}

	.form-actions {
		align-items: center;
		margin-top: 34px;
	}

	.primary,
	.secondary {
		border: 1px solid var(--foreground);
		padding: 13px 18px;
		cursor: pointer;
		font: inherit;
	}

	.primary {
		background: var(--foreground);
		color: var(--background);
	}

	.primary:disabled {
		cursor: wait;
		opacity: 0.55;
	}

	.secondary {
		background: transparent;
	}

	.small {
		padding: 9px 12px;
		font-size: 11px;
	}

	.photo-step {
		display: grid;
		gap: 26px;
	}

	.upload-copy h3,
	.modifications h3 {
		margin: 6px 0;
		font-family: var(--font-display);
		font-size: 34px;
		text-transform: uppercase;
	}

	.upload-copy p:last-child,
	.empty-state {
		margin: 0;
		color: var(--muted);
	}

	.dropzone {
		display: grid;
		justify-items: center;
		gap: 8px;
		padding: 36px 20px;
		border: 1px dashed var(--border);
		text-align: center;
		cursor: pointer;
	}

	.dropzone input {
		display: none;
	}

	.upload-icon {
		font-size: 32px;
	}

	.dropzone small {
		color: var(--muted);
	}

	.preview-grid {
		display: grid;
		grid-template-columns: repeat(5, 1fr);
		gap: 10px;
	}

	.preview-grid figure {
		position: relative;
		min-width: 0;
		margin: 0;
	}

	.preview-grid img {
		display: block;
		width: 100%;
		aspect-ratio: 1;
		object-fit: cover;
	}

	.preview-grid figure button {
		position: absolute;
		top: 3px;
		right: 5px;
		color: white;
		text-shadow: 0 1px 4px black;
	}

	.preview-grid figcaption {
		position: absolute;
		bottom: 5px;
		left: 5px;
		padding: 3px 6px;
		background: var(--foreground);
		color: var(--background);
		font-size: 9px;
		text-transform: uppercase;
	}

	.modifications {
		padding-top: 20px;
		border-top: 1px solid var(--border);
	}

	.modification-row {
		display: flex;
		gap: 8px;
		margin-top: 10px;
	}

	.modification-row input {
		flex: 1;
	}

	@media (max-width: 600px) {
		.form-grid {
			grid-template-columns: 1fr;
		}

		label.full {
			grid-column: auto;
		}

		.ticket-summary {
			grid-template-columns: 1fr;
		}

		.preview-grid {
			grid-template-columns: repeat(3, 1fr);
		}

		.submission-header h2 {
			font-size: 58px;
		}
	}
</style>
