// src/components/admin/event-products-manager.tsx
import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '~/components/ui/card';
import { Button } from '~/components/ui/button';
import { Badge } from '~/components/ui/badge';
import { Checkbox } from '~/components/ui/checkbox';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '~/components/ui/select';
import { Input } from '~/components/ui/input';
import { Label } from '~/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '~/components/ui/tabs';
import { toast } from 'sonner';
import { apiClient } from '~/lib/api';
import { Plus, X, Package, Shirt, Tag, Link as LinkIcon, Loader2 } from 'lucide-react';

interface EventProductsManagerProps {
	eventId: string;
	eventName: string;
	tiers?: any[];
}

interface Product {
	id: string;
	name: string;
	description?: string;
	images?: string[];
	price?: {
		id: string;
		unit_amount: number;
		currency: string;
	};
	metadata?: Record<string, string>;
}

interface TierProduct {
	id: string;
	name: string;
	quantity: number;
}

export function EventProductsManager({ eventId, eventName, tiers = [] }: EventProductsManagerProps) {
	const [linkedProducts, setLinkedProducts] = useState<Product[]>([]);
	const [availableProducts, setAvailableProducts] = useState<Product[]>([]);
	const [tierProducts, setTierProducts] = useState<Record<string, TierProduct[]>>({});
	const [loading, setLoading] = useState(false);
	const [selectedProducts, setSelectedProducts] = useState<string[]>([]);
	const [productQuantities, setProductQuantities] = useState<Record<string, number>>({});

	useEffect(() => {
		fetchLinkedProducts();
		fetchAvailableProducts();
	}, [eventId]);

	const fetchLinkedProducts = async () => {
		try {
			const response = await apiClient.get(`/admin/events/${eventId}/linked-products`);
			setLinkedProducts(response.data.linkedProducts || []);

			// Parse tier products
			const tierProds: Record<string, TierProduct[]> = {};
			(response.data.tierProducts || []).forEach((tier: any) => {
				tierProds[tier.tierId] = tier.includedProducts || [];
			});
			setTierProducts(tierProds);
		} catch (error) {
			console.error('Failed to fetch linked products:', error);
		}
	};

	const fetchAvailableProducts = async () => {
		try {
			const response = await apiClient.get('/products');
			// Filter out events and already linked products
			const products = response.data.products.filter((p: any) =>
				p.metadata?.type !== 'event' &&
				!linkedProducts.find(lp => lp.id === p.id)
			);
			setAvailableProducts(products);
		} catch (error) {
			console.error('Failed to fetch products:', error);
		}
	};

	const linkProducts = async () => {
		if (selectedProducts.length === 0) {
			toast.error('Please select at least one product');
			return;
		}

		setLoading(true);
		try {
			await apiClient.post(`/admin/events/${eventId}/link-products`, {
				eventId,
				productIds: selectedProducts
			});

			toast.success('Products linked successfully');
			setSelectedProducts([]);
			await fetchLinkedProducts();
			await fetchAvailableProducts();
		} catch (error) {
			toast.error('Failed to link products');
		} finally {
			setLoading(false);
		}
	};

	const unlinkProduct = async (productId: string) => {
		setLoading(true);
		try {
			await apiClient.delete(`/admin/events/${eventId}/products/${productId}`);
			toast.success('Product unlinked');
			await fetchLinkedProducts();
			await fetchAvailableProducts();
		} catch (error) {
			toast.error('Failed to unlink product');
		} finally {
			setLoading(false);
		}
	};

	const addProductToTier = async (tierId: string, productId: string, quantity: number) => {
		setLoading(true);
		try {
			const currentProducts = tierProducts[tierId] || [];

			// Check if product already exists in tier
			if (currentProducts.find(p => p.id === productId)) {
				toast.error('Product already included in this tier');
				setLoading(false);
				return;
			}

			// Find product details
			const product = [...linkedProducts, ...availableProducts].find(p => p.id === productId);
			if (!product) {
				toast.error('Product not found');
				setLoading(false);
				return;
			}

			const newProducts = [
				...currentProducts,
				{ productId, quantity }
			];

			await apiClient.post('/admin/tiers/add-products', {
				priceId: tierId,
				products: newProducts
			});

			toast.success('Product added to tier');
			await fetchLinkedProducts();
		} catch (error) {
			toast.error('Failed to add product to tier');
		} finally {
			setLoading(false);
		}
	};

	const removeProductFromTier = async (tierId: string, productId: string) => {
		setLoading(true);
		try {
			const currentProducts = tierProducts[tierId] || [];
			const newProducts = currentProducts.filter(p => p.id !== productId);

			await apiClient.post('/admin/tiers/add-products', {
				priceId: tierId,
				products: newProducts.map(p => ({ productId: p.id, quantity: p.quantity || 1 }))
			});

			toast.success('Product removed from tier');
			await fetchLinkedProducts();
		} catch (error) {
			toast.error('Failed to remove product from tier');
		} finally {
			setLoading(false);
		}
	};

	const updateProductQuantity = async (tierId: string, productId: string, quantity: number) => {
		if (quantity < 1) return;

		setLoading(true);
		try {
			const currentProducts = tierProducts[tierId] || [];
			const updatedProducts = currentProducts.map(p =>
				p.id === productId ? { ...p, quantity } : p
			);

			await apiClient.post('/admin/tiers/add-products', {
				priceId: tierId,
				products: updatedProducts.map(p => ({ productId: p.id, quantity: p.quantity || 1 }))
			});

			toast.success('Quantity updated');
			await fetchLinkedProducts();
		} catch (error) {
			toast.error('Failed to update quantity');
		} finally {
			setLoading(false);
		}
	};

	const toggleProductSelection = (productId: string) => {
		setSelectedProducts(prev => {
			if (prev.includes(productId)) {
				return prev.filter(id => id !== productId);
			}
			return [...prev, productId];
		});
	};

	return (
		<Card>
			<CardHeader>
				<CardTitle>Event Products & Add-ons</CardTitle>
				<CardDescription>
					Manage products linked to {eventName}
				</CardDescription>
			</CardHeader>
			<CardContent>
				<Tabs defaultValue="linked">
					<TabsList className="grid w-full grid-cols-3">
						<TabsTrigger value="linked">Linked Products</TabsTrigger>
						<TabsTrigger value="tiers">Tier Bundles</TabsTrigger>
						<TabsTrigger value="add">Add Products</TabsTrigger>
					</TabsList>

					<TabsContent value="linked" className="space-y-4">
						<div className="text-sm text-muted-foreground mb-4">
							These products are available as add-ons when purchasing event tickets.
						</div>

						{linkedProducts.length === 0 ? (
							<div className="text-center py-8 border-2 border-dashed rounded-lg">
								<Package className="w-12 h-12 mx-auto text-muted-foreground mb-2" />
								<p className="text-muted-foreground">No products linked to this event</p>
								<p className="text-sm text-muted-foreground">Add products in the "Add Products" tab</p>
							</div>
						) : (
							<div className="space-y-2">
								{linkedProducts.map(product => (
									<div key={product.id} className="flex items-center justify-between p-3 border rounded-lg hover:bg-accent/50 transition-colors">
										<div className="flex items-center gap-3">
											{product.images?.[0] ? (
												<img
													src={product.images[0]}
													alt={product.name}
													className="w-12 h-12 object-cover rounded"
												/>
											) : (
												<div className="w-12 h-12 bg-muted rounded flex items-center justify-center">
													<Package className="w-6 h-6 text-muted-foreground" />
												</div>
											)}
											<div>
												<div className="font-medium">{product.name}</div>
												{product.price && (
													<div className="text-sm text-muted-foreground">
														${(product.price.unit_amount / 100).toFixed(2)}
													</div>
												)}
											</div>
										</div>
										<Button
											variant="ghost"
											size="sm"
											onClick={() => unlinkProduct(product.id)}
											disabled={loading}
										>
											<X className="w-4 h-4" />
										</Button>
									</div>
								))}
							</div>
						)}
					</TabsContent>

					<TabsContent value="tiers" className="space-y-4">
						<div className="text-sm text-muted-foreground mb-4">
							Include products with specific ticket tiers. Customers buying these tiers will automatically receive the included products.
						</div>

						{tiers.length === 0 ? (
							<div className="text-center py-8 border-2 border-dashed rounded-lg">
								<Tag className="w-12 h-12 mx-auto text-muted-foreground mb-2" />
								<p className="text-muted-foreground">This event doesn't have tiers</p>
								<p className="text-sm text-muted-foreground">Create tiers in the event settings</p>
							</div>
						) : (
							<div className="space-y-4">
								{tiers.map(tier => (
									<Card key={tier.id || tier.priceId}>
										<CardHeader>
											<div className="flex justify-between items-start">
												<div>
													<CardTitle className="text-base">{tier.name}</CardTitle>
													<CardDescription>
														${(tier.amount).toFixed(2)} {tier.currency?.toUpperCase()}
													</CardDescription>
												</div>
												<Badge variant="outline">Tier</Badge>
											</div>
										</CardHeader>
										<CardContent>
											<div className="space-y-3">
												<Label>Included Products</Label>
												{tierProducts[tier.priceId]?.length > 0 ? (
													<div className="space-y-2">
														{tierProducts[tier.priceId].map((product: TierProduct) => (
															<div key={product.id} className="flex items-center justify-between p-2 bg-muted rounded">
																<div className="flex items-center gap-2">
																	<Shirt className="w-4 h-4" />
																	<span className="text-sm font-medium">{product.name}</span>
																</div>
																<div className="flex items-center gap-2">
																	<div className="flex items-center gap-1">
																		<Button
																			variant="ghost"
																			size="sm"
																			onClick={() => updateProductQuantity(tier.priceId, product.id, product.quantity - 1)}
																			disabled={loading || product.quantity <= 1}
																		>
																			-
																		</Button>
																		<Badge variant="secondary" className="min-w-[40px] justify-center">
																			{product.quantity}x
																		</Badge>
																		<Button
																			variant="ghost"
																			size="sm"
																			onClick={() => updateProductQuantity(tier.priceId, product.id, product.quantity + 1)}
																			disabled={loading}
																		>
																			+
																		</Button>
																	</div>
																	<Button
																		variant="ghost"
																		size="sm"
																		onClick={() => removeProductFromTier(tier.priceId, product.id)}
																		disabled={loading}
																	>
																		<X className="w-3 h-3" />
																	</Button>
																</div>
															</div>
														))}
													</div>
												) : (
													<p className="text-sm text-muted-foreground py-4 text-center border-2 border-dashed rounded">
														No products included in this tier
													</p>
												)}

												<div className="flex gap-2 mt-4">
													<Select
														value=""
														onValueChange={(productId) => {
															if (productId) {
																const quantity = productQuantities[productId] || 1;
																addProductToTier(tier.priceId, productId, quantity);
															}
														}}
														disabled={loading}
													>
														<SelectTrigger>
															<SelectValue placeholder="Add product to tier" />
														</SelectTrigger>
														<SelectContent>
															{[...linkedProducts, ...availableProducts].map(product => (
																<SelectItem key={product.id} value={product.id}>
																	{product.name} - ${((product.price?.unit_amount || 0) / 100).toFixed(2)}
																</SelectItem>
															))}
														</SelectContent>
													</Select>
												</div>
											</div>
										</CardContent>
									</Card>
								))}
							</div>
						)}
					</TabsContent>

					<TabsContent value="add" className="space-y-4">
						<div className="text-sm text-muted-foreground mb-4">
							Select products to link as add-ons for this event. Linked products can be offered during checkout.
						</div>

						{availableProducts.length === 0 ? (
							<div className="text-center py-8 border-2 border-dashed rounded-lg">
								<Package className="w-12 h-12 mx-auto text-muted-foreground mb-2" />
								<p className="text-muted-foreground">No available products to link</p>
								<p className="text-sm text-muted-foreground">Create more products in the Products section</p>
							</div>
						) : (
							<>
								<div className="space-y-2 max-h-96 overflow-y-auto">
									{availableProducts.map(product => (
										<div key={product.id} className="flex items-center space-x-3 p-3 border rounded-lg hover:bg-accent/50 transition-colors">
											<Checkbox
												id={product.id}
												checked={selectedProducts.includes(product.id)}
												onCheckedChange={() => toggleProductSelection(product.id)}
												disabled={loading}
											/>
											<label
												htmlFor={product.id}
												className="flex-1 flex items-center gap-3 cursor-pointer"
											>
												{product.images?.[0] ? (
													<img
														src={product.images[0]}
														alt={product.name}
														className="w-10 h-10 object-cover rounded"
													/>
												) : (
													<div className="w-10 h-10 bg-muted rounded flex items-center justify-center">
														<Package className="w-5 h-5 text-muted-foreground" />
													</div>
												)}
												<div className="flex-1">
													<div className="font-medium">{product.name}</div>
													{product.price && (
														<div className="text-sm text-muted-foreground">
															${(product.price.unit_amount / 100).toFixed(2)}
														</div>
													)}
												</div>
											</label>
										</div>
									))}
								</div>

								<Button
									onClick={linkProducts}
									disabled={loading || selectedProducts.length === 0}
									className="w-full"
								>
									{loading ? (
										<>
											<Loader2 className="w-4 h-4 mr-2 animate-spin" />
											Linking Products...
										</>
									) : (
										<>
											<LinkIcon className="w-4 h-4 mr-2" />
											Link Selected Products ({selectedProducts.length})
										</>
									)}
								</Button>
							</>
						)}
					</TabsContent>
				</Tabs>
			</CardContent>
		</Card>
	);
}

// ui/src/lib/components/admin/event-products-manager.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { toast } from "svelte-sonner";

	import { apiClient } from "$lib/api";
	import { Button } from "$lib/components/ui/button";
	import { Card } from "$lib/components/ui/card";
	import { Checkbox } from "$lib/components/ui/checkbox";

	import type { IncludedProduct } from "$lib/schemas/event";
	import type { Price } from "$lib/schemas/price";
	import type { Product } from "$lib/schemas/product";

	type Tab = "linked" | "prices" | "add";

	interface Props {
		/**
		 * Database event ID.
		 *
		 * Used by admin mutation endpoints.
		 */
		eventId: string;
		eventName: string;
		prices?: Price[];
	}

	interface LinkedProduct {
		id: string;
		name: string;
		description?: string;
		images?: string[];
		active: boolean;
		sort_order: number;
		default_price?: {
			id: string;
			unit_amount: number;
			currency: string;
		};
	}

	interface TierProducts {
		tierId: string;
		tierName: string;
		amount: number;
		currency: string;
		included_products?: IncludedProduct[];
	}

	interface LinkedProductsResponse {
		event_id: string;
		event_name: string;
		linked_products?: LinkedProduct[];
		tier_products?: TierProducts[];
	}

	let { eventId, eventName, prices = [] }: Props = $props();

	let activeTab = $state<Tab>("linked");

	let allProducts = $state<Product[]>([]);
	let linkedProductIds = $state<string[]>([]);
	let tierProducts = $state<Record<string, IncludedProduct[]>>({});

	let selectedProducts = $state<string[]>([]);
	let isLoading = $state(true);
	let isSaving = $state(false);
	let errorMessage = $state("");

	let linkedProducts = $derived(
		allProducts.filter((product) => linkedProductIds.includes(product.id)),
	);

	let availableProducts = $derived(
		allProducts.filter((product) => !linkedProductIds.includes(product.id)),
	);

	const tabs: Array<{ value: Tab; label: string }> = [
		{ value: "linked", label: "Linked products" },
		{ value: "prices", label: "Tier bundles" },
		{ value: "add", label: "Add products" },
	];

	function normalizeProducts(products: Product[]): Product[] {
		return products.filter((product) => product.type !== "event");
	}

	async function loadCatalogProducts() {
		const response = await apiClient.get<{ products: Product[] }>(
			"/products",
		);

		allProducts = normalizeProducts(response.products ?? []);
	}

	async function loadEventProducts() {
		const response = await apiClient.get<LinkedProductsResponse>(
			`/events/${encodeURIComponent(eventId)}/linked-products`,
		);

		linkedProductIds = (response.linked_products ?? []).map(
			(product) => product.id,
		);

		const nextTierProducts: Record<string, IncludedProduct[]> = {};

		for (const tier of response.tier_products ?? []) {
			nextTierProducts[tier.tierId] = tier.included_products ?? [];
		}

		tierProducts = nextTierProducts;
	}

	async function reload() {
		isLoading = true;
		errorMessage = "";

		try {
			await loadCatalogProducts();
			await loadEventProducts();
		} catch (error) {
			console.error("Loading event products failed:", error);
			errorMessage = "Unable to load event products.";
		} finally {
			isLoading = false;
		}
	}

	function toggleProduct(productId: string, checked: boolean) {
		selectedProducts = checked
			? [...selectedProducts, productId]
			: selectedProducts.filter((id) => id !== productId);
	}

	async function linkSelectedProducts() {
		if (selectedProducts.length === 0) {
			toast.error("Select at least one product.");
			return;
		}

		isSaving = true;

		try {
			await apiClient.post(`/admin/events/${eventId}/link-products`, {
				productIds: selectedProducts,
			});

			toast.success("Products linked.");
			selectedProducts = [];

			await reload();
		} catch (error) {
			console.error("Linking products failed:", error);
			toast.error("Unable to link products.");
		} finally {
			isSaving = false;
		}
	}

	async function unlinkProduct(productId: string) {
		isSaving = true;

		try {
			await apiClient.delete(
				`/admin/events/${eventId}/products/${productId}`,
			);

			toast.success("Product unlinked.");
			await reload();
		} catch (error) {
			console.error("Unlinking product failed:", error);
			toast.error("Unable to unlink product.");
		} finally {
			isSaving = false;
		}
	}

	async function saveTierProducts(
		tierId: string,
		products: IncludedProduct[],
	) {
		isSaving = true;

		try {
			const response = await apiClient.put<{
				included_products?: IncludedProduct[];
			}>(`/admin/events/${eventId}/tiers/${tierId}/products`, {
				included_products: products.map((product) => ({
					product_id: product.id,
					quantity: product.quantity,
				})),
			});

			tierProducts = {
				...tierProducts,
				[tierId]: response.included_products ?? products,
			};
		} catch (error) {
			console.error("Updating tier products failed:", error);
			throw error;
		} finally {
			isSaving = false;
		}
	}

	async function addProductToTier(tierId: string, productId: string) {
		const currentProducts = tierProducts[tierId] ?? [];

		if (currentProducts.some((product) => product.id === productId)) {
			toast.error("Product is already included in this tier.");
			return;
		}

		const product = allProducts.find((item) => item.id === productId);

		if (!product) {
			toast.error("Product not found.");
			return;
		}

		try {
			await saveTierProducts(tierId, [
				...currentProducts,
				{
					id: product.id,
					name: product.name,
					description: product.description,
					images: product.images,
					quantity: 1,
				},
			]);

			toast.success("Product added to tier.");
		} catch {
			toast.error("Unable to add product to tier.");
		}
	}

	async function removeProductFromTier(tierId: string, productId: string) {
		const currentProducts = tierProducts[tierId] ?? [];

		try {
			await saveTierProducts(
				tierId,
				currentProducts.filter((product) => product.id !== productId),
			);

			toast.success("Product removed from tier.");
		} catch {
			toast.error("Unable to remove product from tier.");
		}
	}

	async function updateProductQuantity(
		tierId: string,
		productId: string,
		quantity: number,
	) {
		if (quantity < 1) return;

		const currentProducts = tierProducts[tierId] ?? [];

		const updatedProducts = currentProducts.map((product) =>
			product.id === productId ? { ...product, quantity } : product,
		);

		try {
			await saveTierProducts(tierId, updatedProducts);
			toast.success("Quantity updated.");
		} catch {
			toast.error("Unable to update quantity.");
		}
	}

	function formatProductPrice(product: Product) {
		return `$${(product.price / 100).toFixed(2)}`;
	}

	function formatTierPrice(price: Price) {
		return `$${(price.unit_amount / 100).toFixed(2)} ${price.currency.toUpperCase()}`;
	}

	onMount(reload);
</script>

<Card class="space-y-6 p-5">
	<div>
		<h2 class="text-lg font-semibold">Event products and add-ons</h2>

		<p class="text-sm text-muted-foreground">
			Manage products linked to {eventName}.
		</p>
	</div>

	<div class="grid grid-cols-3 rounded-xl border p-1">
		{#each tabs as tab (tab.value)}
			<button
				type="button"
				class={[
					"rounded-lg px-3 py-2 text-sm transition-colors",
					activeTab === tab.value
						? "bg-foreground text-background"
						: "text-muted-foreground hover:text-foreground",
				]}
				onclick={() => (activeTab = tab.value)}
			>
				{tab.label}
			</button>
		{/each}
	</div>

	{#if errorMessage}
		<p
			role="alert"
			class="rounded-xl border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive"
		>
			{errorMessage}
		</p>
	{/if}

	{#if isLoading}
		<p class="text-sm text-muted-foreground">Loading event products…</p>
	{:else if activeTab === "linked"}
		<section class="space-y-4">
			<p class="text-sm text-muted-foreground">
				These products are available as add-ons during event checkout.
			</p>

			{#if linkedProducts.length === 0}
				<div class="rounded-xl border border-dashed p-8 text-center">
					<p class="text-sm text-muted-foreground">
						No products are linked to this event.
					</p>
				</div>
			{:else}
				<div class="space-y-2">
					{#each linkedProducts as product (product.id)}
						<div
							class="flex items-center justify-between gap-4 rounded-xl border p-3"
						>
							<div class="flex min-w-0 items-center gap-3">
								{#if product.images[0]}
									<img
										src={product.images[0]}
										alt={product.name}
										class="h-12 w-12 rounded object-cover"
									/>
								{:else}
									<div
										class="flex h-12 w-12 items-center justify-center rounded bg-muted text-xs"
										aria-hidden="true"
									>
										—
									</div>
								{/if}

								<div class="min-w-0">
									<p class="truncate font-medium">
										{product.name}
									</p>

									<p class="text-sm text-muted-foreground">
										{formatProductPrice(product)}
									</p>
								</div>
							</div>

							<Button
								type="button"
								variant="ghost"
								disabled={isSaving}
								onclick={() => unlinkProduct(product.id)}
							>
								Unlink
							</Button>
						</div>
					{/each}
				</div>
			{/if}
		</section>
	{:else if activeTab === "prices"}
		<section class="space-y-4">
			<p class="text-sm text-muted-foreground">
				Include products with specific ticket prices. Customers buying
				those prices will receive the included products.
			</p>

			{#if prices.length === 0}
				<div class="rounded-xl border border-dashed p-8 text-center">
					<p class="text-sm text-muted-foreground">
						This event does not have any ticket prices.
					</p>
				</div>
			{:else}
				{#each prices as price (price.id)}
					<Card class="space-y-4 border p-4 shadow-none">
						<div>
							<h3 class="font-medium">
								{price.nickname || "Standard"}
							</h3>

							<p class="text-sm text-muted-foreground">
								{formatTierPrice(price)}
							</p>
						</div>

						{#if (tierProducts[price.id] ?? []).length === 0}
							<p
								class="rounded-xl border border-dashed p-4 text-center text-sm text-muted-foreground"
							>
								No products included in this tier.
							</p>
						{:else}
							<div class="space-y-2">
								{#each tierProducts[price.id] ?? [] as product (product.id)}
									<div
										class="flex items-center justify-between gap-3 rounded-lg bg-muted p-2"
									>
										<p
											class="min-w-0 flex-1 truncate text-sm font-medium"
										>
											{product.name}
										</p>

										<div class="flex items-center gap-1">
											<Button
												type="button"
												variant="ghost"
												size="sm"
												disabled={isSaving ||
													product.quantity <= 1}
												onclick={() =>
													updateProductQuantity(
														price.id,
														product.id,
														product.quantity - 1,
													)}
											>
												−
											</Button>

											<span
												class="min-w-10 text-center text-sm"
											>
												{product.quantity}×
											</span>

											<Button
												type="button"
												variant="ghost"
												size="sm"
												disabled={isSaving}
												onclick={() =>
													updateProductQuantity(
														price.id,
														product.id,
														product.quantity + 1,
													)}
											>
												+
											</Button>

											<Button
												type="button"
												variant="ghost"
												size="sm"
												disabled={isSaving}
												onclick={() =>
													removeProductFromTier(
														price.id,
														product.id,
													)}
											>
												Remove
											</Button>
										</div>
									</div>
								{/each}
							</div>
						{/if}

						<select
							class="w-full rounded-xl border bg-background px-3 py-2 text-sm"
							disabled={isSaving}
							onchange={(event) => {
								const select =
									event.currentTarget as HTMLSelectElement;
								const productId = select.value;

								if (productId) {
									void addProductToTier(price.id, productId);
									select.value = "";
								}
							}}
						>
							<option value=""> Add product to tier </option>

							{#each allProducts as product (product.id)}
								<option value={product.id}>
									{product.name} ·
									{formatProductPrice(product)}
								</option>
							{/each}
						</select>
					</Card>
				{/each}
			{/if}
		</section>
	{:else}
		<section class="space-y-4">
			<p class="text-sm text-muted-foreground">
				Select products to link as add-ons for this event.
			</p>

			{#if availableProducts.length === 0}
				<div class="rounded-xl border border-dashed p-8 text-center">
					<p class="text-sm text-muted-foreground">
						No available products to link.
					</p>
				</div>
			{:else}
				<div class="max-h-96 space-y-2 overflow-y-auto">
					{#each availableProducts as product (product.id)}
						<label
							class="flex cursor-pointer items-center gap-3 rounded-xl border p-3 hover:bg-muted/50"
						>
							<Checkbox
								checked={selectedProducts.includes(product.id)}
								disabled={isSaving}
								onCheckedChange={(value) =>
									toggleProduct(product.id, value === true)}
							/>

							<div class="min-w-0 flex-1">
								<p class="truncate font-medium">
									{product.name}
								</p>

								<p class="text-sm text-muted-foreground">
									{formatProductPrice(product)}
								</p>
							</div>
						</label>
					{/each}
				</div>

				<Button
					type="button"
					class="w-full"
					disabled={isSaving || selectedProducts.length === 0}
					onclick={linkSelectedProducts}
				>
					Link selected products ({selectedProducts.length})
				</Button>
			{/if}
		</section>
	{/if}
</Card>
