// src/components/admin/submission-issues-manager.tsx
// euro-haus/src/components/admin/submission-issues-manager.tsx
import React, { useState, useEffect } from 'react';
import { format } from 'date-fns';
import {
	AlertTriangle,
	Mail,
	DollarSign,
	CheckCircle,
	ExternalLink,
	Loader2,
	RefreshCw,
	User,
	AlertCircle,
	Filter,
	Search,
	X,
} from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '~/components/ui/card';
import { Button } from '~/components/ui/button';
import { Badge } from '~/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '~/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '~/components/ui/select';
import { Alert, AlertDescription } from '~/components/ui/alert';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '~/components/ui/tabs';
import { toast } from 'sonner';
import { submissionService, type PaymentStatus } from '~/lib/services/submission-service';
import { apiClient } from '~/lib/api';
import { Input } from '~/components/ui/input';
import { Checkbox } from '~/components/ui/checkbox';
import { Switch } from '~/components/ui/switch';
import { Label } from '~/components/ui/label';
import type { VehicleSubmission } from '~/lib/interfaces/submission';
import type { StripeProduct } from '~/lib/services/stripe-service';
import { getRouteApi, useNavigate } from '@tanstack/react-router';

interface SubmissionWithIssues extends VehicleSubmission {
	issues?: string[];
}

interface EventPrice {
	id: string;
	label: string;
	amount: number;
}

interface PriceResponse {
	id: string;
	nickname?: string;
	unit_amount: number;
	active: boolean;
}

interface SubmissionIssuesManagerProps {
	submissions: SubmissionWithIssues[];
	events: StripeProduct[];
}

interface FilterOptions {
	debug: boolean;
	all: boolean;
	includeId: string;
	issueType: string[];
	status: string[];
	searchTerm: string;
}

export function SubmissionIssuesManager({ submissions, events }: SubmissionIssuesManagerProps) {
	const routeApi = getRouteApi('/admin/submission-issues');
	const { debug, all, include_id } = routeApi.useSearch();
	const navigate = useNavigate();
	const [selectedSubmission, setSelectedSubmission] = useState<SubmissionWithIssues | null>(null);
	const [paymentStatus, setPaymentStatus] = useState<PaymentStatus | null>(null);
	const [isCheckingPayment, setIsCheckingPayment] = useState(false);
	const [isCreatingPayment, setIsCreatingPayment] = useState(false);
	const [isResendingEmail, setIsResendingEmail] = useState(false);
	const [selectedPriceId, setSelectedPriceId] = useState<string>('');
	const [showPaymentDialog, setShowPaymentDialog] = useState(false);
	const [eventPrices, setEventPrices] = useState<EventPrice[]>([]);
	const [isLoadingPrices, setIsLoadingPrices] = useState(false);
	const [showFilterDialog, setShowFilterDialog] = useState(false);

	// Filter states
	const [filterOptions, setFilterOptions] = useState<FilterOptions>({
		debug: debug === true,
		all: all === true,
		includeId: include_id || '',
		issueType: [],
		status: [],
		searchTerm: '',
	});

	// Apply filters from URL on component mount
	useEffect(() => {
		setFilterOptions(prev => ({
			...prev,
			debug: debug === true,
			all: all === true,
			includeId: include_id || '',
		}));
	}, [debug, all, include_id]);

	// Filtered submissions
	const filteredSubmissions = submissions.filter(submission => {
		// Apply search filter
		if (filterOptions.searchTerm) {
			const searchLower = filterOptions.searchTerm.toLowerCase();
			const matchesSearch =
				submission.participantName?.toLowerCase().includes(searchLower) ||
				submission.participantEmail?.toLowerCase().includes(searchLower) ||
				submission.vehicleMake?.toLowerCase().includes(searchLower) ||
				submission.vehicleModel?.toLowerCase().includes(searchLower) ||
				submission.id?.toLowerCase().includes(searchLower);

			if (!matchesSearch) return false;
		}

		// Apply status filter
		if (filterOptions.status.length > 0 && !filterOptions.status.includes(submission.status)) {
			return false;
		}

		// Apply issue type filter
		if (filterOptions.issueType.length > 0) {
			const hasMatchingIssue = submission.issues?.some(issue =>
				filterOptions.issueType.includes(issue)
			);
			if (!hasMatchingIssue) return false;
		}

		return true;
	});

	// Group submissions by issue type
	const paymentIssues = filteredSubmissions.filter(s =>
		s.issues?.some(i => ['no_payment', 'payment_failed', 'payment_expired', 'payment_incomplete',
			'missing_payment_intent', 'payment_intent_check_failed', 'payment_not_succeeded',
			'missing_checkout_data', 'incomplete_payment_process'].includes(i))
	);

	const emailIssues = filteredSubmissions.filter(s =>
		s.issues?.includes('email_not_sent')
	);

	const ticketIssues = filteredSubmissions.filter(s =>
		s.issues?.includes('no_ticket_created')
	);

	const allIssues = filteredSubmissions;

	// Load event prices when a submission is selected for payment
	useEffect(() => {
		if (selectedSubmission && showPaymentDialog) {
			loadEventPrices(selectedSubmission.eventId);
		}
	}, [selectedSubmission, showPaymentDialog]);

	// Apply filters via URL parameters
	const applyFilters = () => {
		const params: Record<string, string> = {};

		if (filterOptions.debug) params.debug = 'true';
		if (filterOptions.all) params.all = 'true';
		if (filterOptions.includeId) params.include_id = filterOptions.includeId;

		navigate({
			to: '/admin/submission-issues',
			search: {
				...params
			}
		})
		setShowFilterDialog(false);

		toast.info('Filters applied')
	};

	const loadEventPrices = async (eventId: string) => {
		setIsLoadingPrices(true);
		setEventPrices([]);
		try {
			const response = await apiClient.get<{ prices: PriceResponse[] }>(`/products/${eventId}/prices`);
			const prices = response.data.prices || [];

			const formattedPrices = prices
				.filter(p => p.active)
				.map(p => ({
					id: p.id,
					label: `${p.nickname || 'Ticket'} - $${(p.unit_amount / 100).toFixed(2)}`,
					amount: p.unit_amount,
				}));

			setEventPrices(formattedPrices);

			// Auto-select first price if only one available
			if (formattedPrices.length === 1) {
				setSelectedPriceId(formattedPrices[0].id);
			}
		} catch {
			toast.error('Failed to load ticket prices');
		} finally {
			setIsLoadingPrices(false);
		}
	};

	const handleCheckPaymentStatus = async (submission: SubmissionWithIssues) => {
		setIsCheckingPayment(true);
		try {
			const status = await submissionService.getPaymentStatus(submission.id);
			setPaymentStatus(status);
			setSelectedSubmission(submission);
			toast.success('Payment status retrieved');
		} catch {
			toast.error('Failed to check payment status');
		} finally {
			setIsCheckingPayment(false);
		}
	};

	const handleCreatePayment = async () => {
		if (!selectedSubmission || !selectedPriceId) {
			toast.error('Please select a price');
			return;
		}

		setIsCreatingPayment(true);
		try {
			const event = events.find(e => e.id === selectedSubmission.eventId);
			const eventName = event?.name || 'Event';

			const response = await submissionService.createPayment(
				selectedSubmission.id,
				selectedPriceId,
				eventName
			);

			if (response.sessionUrl) {
				toast.success('Payment link created successfully');
				// Open the payment link in a new tab
				window.open(response.sessionUrl, '_blank');
				setShowPaymentDialog(false);
				setSelectedPriceId('');
			}
		} catch {
			toast.error('Failed to create payment');
		} finally {
			setIsCreatingPayment(false);
		}
	};

	const handleResendEmail = async (submission: SubmissionWithIssues) => {
		setIsResendingEmail(true);
		try {
			const response = await submissionService.resendApprovalEmail(submission.id);
			if (response.success) {
				toast.success(response.message || 'Email sent successfully');
			} else {
				toast.error(response.message || 'Failed to send email');
			}
		} catch {
			toast.error('Failed to resend email');
		} finally {
			setIsResendingEmail(false);
		}
	};

	const resetFilters = () => {
		setFilterOptions({
			debug: false,
			all: false,
			includeId: '',
			issueType: [],
			status: [],
			searchTerm: '',
		});
	};

	// Get a list of all unique issue types
	const allIssueTypes = [...new Set(
		submissions.flatMap(submission => submission.issues || [])
	)].sort();

	const SubmissionCard = ({ submission }: { submission: SubmissionWithIssues }) => {
		const event = events.find(e => e.id === submission.eventId);
		const hasPaymentIssue = submission.issues?.some(i =>
			['no_payment', 'payment_failed', 'payment_expired', 'payment_incomplete',
				'missing_payment_intent', 'payment_intent_check_failed', 'payment_not_succeeded',
				'missing_checkout_data', 'incomplete_payment_process'].includes(i)
		);
		const hasEmailIssue = submission.issues?.includes('email_not_sent');
		const hasTicketIssue = submission.issues?.includes('no_ticket_created');

		return (
			<Card className="hover:shadow-lg transition-shadow">
				<CardHeader>
					<div className="flex justify-between items-start">
						<div>
							<CardTitle className="text-lg flex items-center gap-2">
								<User className="h-4 w-4" />
								{submission.participantName}
							</CardTitle>
							<CardDescription className="mt-1 flex items-center gap-1">
								{submission.participantEmail}
								<Badge variant="outline" className="ml-2">{submission.id}</Badge>
							</CardDescription>
						</div>
						<div className="flex flex-col gap-2">
							<Badge className={
								submission.status === 'approved' ? 'bg-green-100 text-green-800' :
									submission.status === 'pending' ? 'bg-yellow-100 text-yellow-800' :
										submission.status === 'denied' ? 'bg-red-100 text-red-800' :
											'bg-gray-100 text-gray-800'
							}>
								{submission.status}
							</Badge>
							{hasPaymentIssue && (
								<Badge variant="destructive" className="flex items-center gap-1">
									<DollarSign className="h-3 w-3" />
									Payment Issue
								</Badge>
							)}
							{hasEmailIssue && (
								<Badge variant="secondary" className="flex items-center gap-1">
									<Mail className="h-3 w-3" />
									Email Issue
								</Badge>
							)}
							{hasTicketIssue && (
								<Badge variant="outline" className="flex items-center gap-1 border-orange-300 text-orange-700">
									<AlertCircle className="h-3 w-3" />
									Ticket Issue
								</Badge>
							)}
						</div>
					</div>
				</CardHeader>
				<CardContent className="space-y-4">
					<div className="grid grid-cols-2 gap-4 text-sm">
						<div>
							<p className="text-muted-foreground">Event</p>
							<p className="font-medium">{event?.name || 'Unknown Event'}</p>
						</div>
						<div>
							<p className="text-muted-foreground">Vehicle</p>
							<p className="font-medium">
								{submission.vehicleYear} {submission.vehicleMake} {submission.vehicleModel}
							</p>
						</div>
						<div>
							<p className="text-muted-foreground">Submitted</p>
							<p className="font-medium">
								{format(new Date(submission.submittedAt), 'MMM d, yyyy')}
							</p>
						</div>
						{submission.reviewedAt && (
							<div>
								<p className="text-muted-foreground">Reviewed</p>
								<p className="font-medium">
									{format(new Date(submission.reviewedAt), 'MMM d, yyyy')}
								</p>
							</div>
						)}
					</div>

					{submission.issues && submission.issues.length > 0 && (
						<Alert className="border-yellow-200 bg-yellow-50">
							<AlertTriangle className="h-4 w-4 text-yellow-600" />
							<AlertDescription className="text-sm">
								<strong>Issues detected:</strong>
								<ul className="mt-1 list-disc list-inside">
									{submission.issues.map((issue, idx) => (
										<li key={idx}>{issue.replace(/_/g, ' ')}</li>
									))}
								</ul>
							</AlertDescription>
						</Alert>
					)}

					<div className="flex flex-wrap gap-2">
						{hasPaymentIssue && (
							<>
								<Button
									size="sm"
									variant="outline"
									onClick={() => handleCheckPaymentStatus(submission)}
									disabled={isCheckingPayment}
								>
									{isCheckingPayment ? (
										<Loader2 className="h-4 w-4 animate-spin" />
									) : (
										<RefreshCw className="h-4 w-4" />
									)}
									Check Payment
								</Button>
								<Button
									size="sm"
									onClick={() => {
										setSelectedSubmission(submission);
										setShowPaymentDialog(true);
									}}
								>
									<DollarSign className="h-4 w-4" />
									Create Payment
								</Button>
							</>
						)}
						{hasEmailIssue && submission.status === 'approved' && (
							<Button
								size="sm"
								variant="outline"
								onClick={() => handleResendEmail(submission)}
								disabled={isResendingEmail}
							>
								{isResendingEmail ? (
									<Loader2 className="h-4 w-4 animate-spin" />
								) : (
									<Mail className="h-4 w-4" />
								)}
								Resend Email
							</Button>
						)}
					</div>
				</CardContent>
				<CardFooter className="text-xs text-muted-foreground pt-0">
					{submission.checkoutSessionId && <span className="mr-2">Session: {submission.checkoutSessionId.substring(0, 8)}...</span>}
					{submission.paymentIntentId && <span className="mr-2">Payment: {submission.paymentIntentId.substring(0, 8)}...</span>}
					{submission.ticketId && <span>Ticket: {submission.ticketId.substring(0, 8)}...</span>}
				</CardFooter>
			</Card>
		);
	};

	return (
		<>
			<div className="flex justify-between items-center mb-6">
				<div className="relative w-full max-w-sm">
					<Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
					<Input
						placeholder="Search by name, email, vehicle..."
						className="pl-9 pr-4"
						value={filterOptions.searchTerm}
						onChange={(e) => setFilterOptions({ ...filterOptions, searchTerm: e.target.value })}
					/>
				</div>
				<div className="flex gap-2">
					<Button variant="outline" onClick={() => setShowFilterDialog(true)}>
						<Filter className="h-4 w-4 mr-2" />
						Filter
						{(filterOptions.debug || filterOptions.all || filterOptions.includeId ||
							filterOptions.status.length > 0 || filterOptions.issueType.length > 0) && (
								<Badge className="ml-2 h-5 w-5 p-0 flex items-center justify-center">
									{[filterOptions.debug, filterOptions.all, filterOptions.includeId !== ''].filter(Boolean).length +
										filterOptions.status.length + filterOptions.issueType.length}
								</Badge>
							)}
					</Button>
				</div>
			</div>

			<Tabs defaultValue="all" className="w-full">
				<TabsList className="grid w-full grid-cols-4">
					<TabsTrigger value="all">
						All Issues ({allIssues.length})
					</TabsTrigger>
					<TabsTrigger value="payment">
						Payment Issues ({paymentIssues.length})
					</TabsTrigger>
					<TabsTrigger value="email">
						Email Issues ({emailIssues.length})
					</TabsTrigger>
					<TabsTrigger value="ticket">
						Ticket Issues ({ticketIssues.length})
					</TabsTrigger>
				</TabsList>

				<TabsContent value="all" className="space-y-4 mt-6">
					{allIssues.length === 0 ? (
						<Card>
							<CardContent className="text-center py-8">
								<CheckCircle className="w-12 h-12 mx-auto text-green-500 mb-4" />
								<p className="text-muted-foreground">No submissions with issues found</p>
								{(filterOptions.debug || filterOptions.all || filterOptions.includeId ||
									filterOptions.status.length > 0 || filterOptions.issueType.length > 0 ||
									filterOptions.searchTerm) && (
										<Button
											variant="link"
											onClick={resetFilters}
											className="mt-2"
										>
											Clear filters
										</Button>
									)}
							</CardContent>
						</Card>
					) : (
						<div className="grid gap-4">
							{allIssues.map((submission) => (
								<SubmissionCard key={submission.id} submission={submission} />
							))}
						</div>
					)}
				</TabsContent>

				<TabsContent value="payment" className="space-y-4 mt-6">
					{paymentIssues.length === 0 ? (
						<Card>
							<CardContent className="text-center py-8">
								<CheckCircle className="w-12 h-12 mx-auto text-green-500 mb-4" />
								<p className="text-muted-foreground">No payment issues found</p>
							</CardContent>
						</Card>
					) : (
						<div className="grid gap-4">
							{paymentIssues.map((submission) => (
								<SubmissionCard key={submission.id} submission={submission} />
							))}
						</div>
					)}
				</TabsContent>

				<TabsContent value="email" className="space-y-4 mt-6">
					{emailIssues.length === 0 ? (
						<Card>
							<CardContent className="text-center py-8">
								<CheckCircle className="w-12 h-12 mx-auto text-green-500 mb-4" />
								<p className="text-muted-foreground">No email issues found</p>
							</CardContent>
						</Card>
					) : (
						<div className="grid gap-4">
							{emailIssues.map((submission) => (
								<SubmissionCard key={submission.id} submission={submission} />
							))}
						</div>
					)}
				</TabsContent>

				<TabsContent value="ticket" className="space-y-4 mt-6">
					{ticketIssues.length === 0 ? (
						<Card>
							<CardContent className="text-center py-8">
								<CheckCircle className="w-12 h-12 mx-auto text-green-500 mb-4" />
								<p className="text-muted-foreground">No ticket issues found</p>
							</CardContent>
						</Card>
					) : (
						<div className="grid gap-4">
							{ticketIssues.map((submission) => (
								<SubmissionCard key={submission.id} submission={submission} />
							))}
						</div>
					)}
				</TabsContent>
			</Tabs>

			{/* Payment Status Modal */}
			{paymentStatus && selectedSubmission && (
				<Dialog open={!!paymentStatus} onOpenChange={() => setPaymentStatus(null)}>
					<DialogContent className="max-w-md">
						<DialogHeader>
							<DialogTitle>Payment Status</DialogTitle>
							<DialogDescription>
								Payment details for {selectedSubmission.participantName}
							</DialogDescription>
						</DialogHeader>
						<div className="space-y-4">
							<div className="flex items-center justify-between">
								<span className="text-sm text-muted-foreground">Has Payment:</span>
								<Badge variant={paymentStatus.hasPayment ? 'default' : 'destructive'}>
									{paymentStatus.hasPayment ? 'Yes' : 'No'}
								</Badge>
							</div>
							{paymentStatus.paymentStatus && (
								<div className="flex items-center justify-between">
									<span className="text-sm text-muted-foreground">Status:</span>
									<span className="font-medium">{paymentStatus.paymentStatus}</span>
								</div>
							)}
							{paymentStatus.paymentAmount && (
								<div className="flex items-center justify-between">
									<span className="text-sm text-muted-foreground">Amount:</span>
									<span className="font-medium">
										${(paymentStatus.paymentAmount / 100).toFixed(2)} {paymentStatus.paymentCurrency?.toUpperCase()}
									</span>
								</div>
							)}
							{paymentStatus.emailSent !== undefined && (
								<div className="flex items-center justify-between">
									<span className="text-sm text-muted-foreground">Email Sent:</span>
									<Badge variant={paymentStatus.emailSent ? 'default' : 'secondary'}>
										{paymentStatus.emailSent ? 'Yes' : 'No'}
									</Badge>
								</div>
							)}
							{paymentStatus.emailSentAt && (
								<div className="flex items-center justify-between">
									<span className="text-sm text-muted-foreground">Email Sent At:</span>
									<span className="font-medium">
										{format(new Date(paymentStatus.emailSentAt), 'MMM d, yyyy h:mm a')}
									</span>
								</div>
							)}
							{paymentStatus.errorMessage && (
								<Alert className="border-red-200 bg-red-50">
									<AlertCircle className="h-4 w-4 text-red-600" />
									<AlertDescription className="text-sm text-red-800">
										{paymentStatus.errorMessage}
									</AlertDescription>
								</Alert>
							)}
							{paymentStatus.checkoutURL && (
								<Button
									className="w-full"
									onClick={() => window.open(paymentStatus.checkoutURL, '_blank')}
								>
									<ExternalLink className="h-4 w-4 mr-2" />
									Open Checkout
								</Button>
							)}
						</div>
					</DialogContent>
				</Dialog>
			)}

			{/* Create Payment Dialog */}
			<Dialog open={showPaymentDialog} onOpenChange={(open) => {
				setShowPaymentDialog(open);
				if (!open) {
					setSelectedPriceId('');
					setEventPrices([]);
				}
			}}>
				<DialogContent>
					<DialogHeader>
						<DialogTitle>Create Payment Link</DialogTitle>
						<DialogDescription>
							Generate a payment link for {selectedSubmission?.participantName}
						</DialogDescription>
					</DialogHeader>
					<div className="space-y-4">
						{isLoadingPrices ? (
							<div className="flex items-center justify-center py-4">
								<Loader2 className="h-6 w-6 animate-spin" />
							</div>
						) : (
							<div>
								<label className="text-sm font-medium">Select Ticket Type</label>
								<Select value={selectedPriceId} onValueChange={setSelectedPriceId}>
									<SelectTrigger className="w-full mt-1">
										<SelectValue placeholder="Choose a ticket type" />
									</SelectTrigger>
									<SelectContent>
										{eventPrices.map((price) => (
											<SelectItem key={price.id} value={price.id}>
												{price.label}
											</SelectItem>
										))}
									</SelectContent>
								</Select>
							</div>
						)}
					</div>
					<DialogFooter>
						<Button variant="outline" onClick={() => setShowPaymentDialog(false)}>
							Cancel
						</Button>
						<Button
							onClick={handleCreatePayment}
							disabled={!selectedPriceId || isCreatingPayment || isLoadingPrices}
						>
							{isCreatingPayment ? (
								<>
									<Loader2 className="h-4 w-4 animate-spin mr-2" />
									Creating...
								</>
							) : (
								'Create Payment Link'
							)}
						</Button>
					</DialogFooter>
				</DialogContent>
			</Dialog>

			{/* Filter Dialog */}
			<Dialog open={showFilterDialog} onOpenChange={setShowFilterDialog}>
				<DialogContent className="max-w-md">
					<DialogHeader>
						<DialogTitle>Filter Submissions</DialogTitle>
						<DialogDescription>
							Customize which submissions are displayed
						</DialogDescription>
					</DialogHeader>
					<div className="space-y-6 py-2">
						<div className="space-y-4">
							<h3 className="text-sm font-medium">Debug Options</h3>

							<div className="flex items-center justify-between">
								<Label htmlFor="debug-mode" className="flex items-center gap-2">
									Debug Mode
									<span className="text-xs text-muted-foreground">(Show all submissions)</span>
								</Label>
								<Switch
									id="debug-mode"
									checked={filterOptions.debug}
									onCheckedChange={(checked) => setFilterOptions({ ...filterOptions, debug: checked })}
								/>
							</div>

							<div className="flex items-center justify-between">
								<Label htmlFor="all-mode" className="flex items-center gap-2">
									Show All
									<span className="text-xs text-muted-foreground">(Including without issues)</span>
								</Label>
								<Switch
									id="all-mode"
									checked={filterOptions.all}
									onCheckedChange={(checked) => setFilterOptions({ ...filterOptions, all: checked })}
								/>
							</div>

							<div className="flex flex-col gap-2">
								<Label htmlFor="include-id">Include Specific Submission ID</Label>
								<Input
									id="include-id"
									placeholder="Enter submission ID"
									value={filterOptions.includeId}
									onChange={(e) => setFilterOptions({ ...filterOptions, includeId: e.target.value })}
								/>
							</div>
						</div>

						<div className="space-y-4">
							<h3 className="text-sm font-medium">Status Filters</h3>
							<div className="grid grid-cols-2 gap-2">
								{['approved', 'pending', 'denied'].map(status => (
									<div key={status} className="flex items-center gap-2">
										<Checkbox
											id={`status-${status}`}
											checked={filterOptions.status.includes(status)}
											onCheckedChange={(checked) => {
												const newStatus = checked
													? [...filterOptions.status, status]
													: filterOptions.status.filter(s => s !== status);
												setFilterOptions({ ...filterOptions, status: newStatus });
											}}
										/>
										<Label htmlFor={`status-${status}`}>{status}</Label>
									</div>
								))}
							</div>
						</div>

						<div className="space-y-4">
							<h3 className="text-sm font-medium">Issue Type Filters</h3>
							<div className="grid grid-cols-1 gap-2 max-h-60 overflow-y-auto">
								{allIssueTypes.map(issue => (
									<div key={issue} className="flex items-center gap-2">
										<Checkbox
											id={`issue-${issue}`}
											checked={filterOptions.issueType.includes(issue)}
											onCheckedChange={(checked) => {
												const newIssues = checked
													? [...filterOptions.issueType, issue]
													: filterOptions.issueType.filter(i => i !== issue);
												setFilterOptions({ ...filterOptions, issueType: newIssues });
											}}
										/>
										<Label htmlFor={`issue-${issue}`}>{issue.replace(/_/g, ' ')}</Label>
									</div>
								))}
							</div>
						</div>
					</div>
					<DialogFooter className="flex justify-between items-center">
						<Button
							variant="ghost"
							onClick={resetFilters}
							className="mr-auto"
						>
							Reset
						</Button>
						<div className="flex gap-2">
							<Button variant="outline" onClick={() => setShowFilterDialog(false)}>
								Cancel
							</Button>
							<Button onClick={applyFilters}>
								Apply Filters
							</Button>
						</div>
					</DialogFooter>
				</DialogContent>
			</Dialog>
		</>
	);
}

// ui/src/lib/components/admin/submission-issues-manager.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { toast } from "svelte-sonner";

	import apiClient from "$lib/api";
	import type { VehicleSubmission } from "$lib/schemas/event";
	import type { Price } from "$lib/schemas/price";

	import * as Form from "$lib/components/ui/form";
	import { Input } from "$lib/components/ui/input";
	import { Button } from "$lib/components/ui/button";
	import { Checkbox } from "$lib/components/ui/checkbox";
	import { Textarea } from "$lib/components/ui/textarea";
	import { Card } from "$lib/components/ui/card";

	interface Props {
		events?: Array<{
			id: string;
			name: string;
		}>;
	}

	type IssueSubmission = VehicleSubmission & {
		issues?: string[];
		event_slug?: string;
		has_issue?: boolean;
		email_sent_at?: string;
	};

	interface IssuesResponse {
		submissions?: IssueSubmission[];
		total?: number;
	}

	interface PaymentStatus {
		has_payment: boolean;
		payment_status?: string;
		payment_amount?: number;
		payment_currency?: string;
		checkout_url?: string;
		error_message?: string;
		email_sent_at?: string;
	}

	interface PaymentResponse {
		success?: boolean;
		sessionUrl?: string;
		sessionId?: string;
		message?: string;
	}

	let { events = [] }: Props = $props();

	let submissions = $state<IssueSubmission[]>([]);
	let loading = $state(true);
	let errorMessage = $state("");

	let activeTab = $state<"all" | "payment" | "email" | "ticket">("all");

	let searchTerm = $state("");
	let selectedStatuses = $state<string[]>([]);
	let selectedIssueTypes = $state<string[]>([]);

	let debugMode = $state(false);
	let showAll = $state(false);
	let includeId = $state("");

	let showFilters = $state(false);
	let showPaymentStatus = $state(false);
	let showCreatePayment = $state(false);

	let selectedSubmission = $state<IssueSubmission | null>(null);
	let paymentStatus = $state<PaymentStatus | null>(null);

	let prices = $state<Price[]>([]);
	let selectedPriceId = $state("");

	let checkingPayment = $state(false);
	let creatingPayment = $state(false);
	let resendingEmail = $state(false);
	let loadingPrices = $state(false);

	const paymentIssueTypes = [
		"no_payment",
		"payment_failed",
		"payment_expired",
		"payment_incomplete",
		"missing_payment_intent",
		"payment_intent_check_failed",
		"payment_not_succeeded",
		"missing_checkout_data",
		"incomplete_payment_process",
	];

	const issueTypes = $derived(
		[
			...new Set(
				submissions.flatMap((submission) => submission.issues ?? []),
			),
		].sort(),
	);

	const filteredSubmissions = $derived(
		submissions.filter((submission) => {
			const query = searchTerm.trim().toLowerCase();

			if (query) {
				const matchesSearch = [
					submission.participant_name,
					submission.participant_email,
					submission.vehicle_make,
					submission.vehicle_model,
					submission.id,
				].some((value) => value?.toLowerCase().includes(query));

				if (!matchesSearch) return false;
			}

			if (
				selectedStatuses.length > 0 &&
				!selectedStatuses.includes(submission.status)
			) {
				return false;
			}

			if (selectedIssueTypes.length > 0) {
				const hasSelectedIssue = (submission.issues ?? []).some(
					(issue) => selectedIssueTypes.includes(issue),
				);

				if (!hasSelectedIssue) return false;
			}

			return true;
		}),
	);

	const paymentIssues = $derived(
		filteredSubmissions.filter((submission) =>
			(submission.issues ?? []).some((issue) =>
				paymentIssueTypes.includes(issue),
			),
		),
	);

	const emailIssues = $derived(
		filteredSubmissions.filter((submission) =>
			(submission.issues ?? []).includes("email_not_sent"),
		),
	);

	const ticketIssues = $derived(
		filteredSubmissions.filter((submission) =>
			(submission.issues ?? []).includes("no_ticket_created"),
		),
	);

	const visibleSubmissions = $derived(
		activeTab === "payment"
			? paymentIssues
			: activeTab === "email"
				? emailIssues
				: activeTab === "ticket"
					? ticketIssues
					: filteredSubmissions,
	);

	onMount(() => {
		void loadSubmissions();
	});

	function formatDate(value?: string): string {
		if (!value) return "—";

		return new Intl.DateTimeFormat(undefined, {
			dateStyle: "medium",
		}).format(new Date(value));
	}

	function getEventName(submission: IssueSubmission): string {
		return (
			events.find((event) => event.id === submission.event_id)?.name ??
			submission.event_slug ??
			"Unknown event"
		);
	}

	function formatIssue(issue: string): string {
		return issue.replaceAll("_", " ");
	}

	function hasPaymentIssue(submission: IssueSubmission): boolean {
		return (submission.issues ?? []).some((issue) =>
			paymentIssueTypes.includes(issue),
		);
	}

	function hasEmailIssue(submission: IssueSubmission): boolean {
		return (submission.issues ?? []).includes("email_not_sent");
	}

	function hasTicketIssue(submission: IssueSubmission): boolean {
		return (submission.issues ?? []).includes("no_ticket_created");
	}

	async function loadSubmissions() {
		loading = true;
		errorMessage = "";

		const params = new URLSearchParams();

		if (debugMode) params.set("debug", "true");
		if (showAll) params.set("all", "true");
		if (includeId.trim()) {
			params.set("include_id", includeId.trim());
		}

		const query = params.toString();

		try {
			const response = await apiClient.get<IssuesResponse>(
				`/admin/submissions/issues${query ? `?${query}` : ""}`,
			);

			submissions = response.submissions ?? [];
		} catch (error) {
			console.error("Failed to load submission issues:", error);
			errorMessage = "Failed to load submission issues.";
		} finally {
			loading = false;
		}
	}

	async function applyServerFilters() {
		showFilters = false;
		await loadSubmissions();
		toast.success("Filters applied.");
	}

	function resetFilters() {
		debugMode = false;
		showAll = false;
		includeId = "";
		searchTerm = "";
		selectedStatuses = [];
		selectedIssueTypes = [];
		showFilters = false;

		void loadSubmissions();
	}

	async function checkPaymentStatus(submission: IssueSubmission) {
		checkingPayment = true;
		selectedSubmission = submission;

		try {
			paymentStatus = await apiClient.get<PaymentStatus>(
				`/admin/submissions/${submission.id}/payment-status`,
			);

			showPaymentStatus = true;
		} catch (error) {
			console.error("Failed to check payment status:", error);
			toast.error("Failed to check payment status.");
		} finally {
			checkingPayment = false;
		}
	}

	async function openCreatePayment(submission: IssueSubmission) {
		selectedSubmission = submission;
		selectedPriceId = "";
		prices = [];
		showCreatePayment = true;

		await loadPrices(submission.event_id);
	}

	async function loadPrices(eventId: string) {
		loadingPrices = true;

		try {
			const response = await apiClient.get<{
				prices?: Price[];
			}>(`/products/${eventId}/prices`);

			prices = (response.prices ?? []).filter((price) => price.active);

			if (prices.length === 1) {
				selectedPriceId = prices[0].id;
			}
		} catch (error) {
			console.error("Failed to load event prices:", error);
			toast.error("Failed to load ticket prices.");
		} finally {
			loadingPrices = false;
		}
	}

	async function createPayment() {
		if (!selectedSubmission || !selectedPriceId) {
			toast.error("Please select a ticket price.");
			return;
		}

		creatingPayment = true;

		try {
			const response = await apiClient.post<PaymentResponse>(
				`/admin/submissions/${selectedSubmission.id}/create-payment`,
				{
					priceId: selectedPriceId,
					eventName: getEventName(selectedSubmission),
				},
			);

			if (response.sessionUrl) {
				toast.success("Payment link created.");

				window.open(response.sessionUrl, "_blank");
				showCreatePayment = false;
				selectedPriceId = "";

				await loadSubmissions();
			}
		} catch (error) {
			console.error("Failed to create payment:", error);
			toast.error("Failed to create payment link.");
		} finally {
			creatingPayment = false;
		}
	}

	async function resendApprovalEmail(submission: IssueSubmission) {
		resendingEmail = true;

		try {
			const response = await apiClient.post<{
				success?: boolean;
				message?: string;
			}>(`/admin/submissions/${submission.id}/resend-email`);

			if (response.success) {
				toast.success(response.message ?? "Approval email resent.");
			} else {
				toast.error(response.message ?? "Failed to resend email.");
			}

			await loadSubmissions();
		} catch (error) {
			console.error("Failed to resend approval email:", error);
			toast.error("Failed to resend approval email.");
		} finally {
			resendingEmail = false;
		}
	}
</script>

{#if loading}
	<div
		class="flex min-h-64 items-center justify-center text-muted-foreground"
	>
		Loading submission issues…
	</div>
{:else}
	<div class="space-y-6">
		{#if errorMessage}
			<p
				role="alert"
				class="rounded-xl border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive"
			>
				{errorMessage}
			</p>
		{/if}

		<div class="flex flex-col gap-3 md:flex-row md:items-center">
			<Input
				bind:value={searchTerm}
				placeholder="Search by name, email, vehicle, or ID..."
				class="md:max-w-sm"
			/>

			<div class="flex gap-2 md:ml-auto">
				<Button
					type="button"
					variant="outline"
					onclick={() => (showFilters = !showFilters)}
				>
					Filters
				</Button>

				<Button
					type="button"
					variant="outline"
					onclick={() => loadSubmissions()}
				>
					Refresh
				</Button>
			</div>
		</div>

		{#if showFilters}
			<Card class="space-y-5 p-5">
				<div>
					<h2 class="font-semibold">Submission filters</h2>

					<p class="text-sm text-muted-foreground">
						Control which issue records are loaded and displayed.
					</p>
				</div>

				<div class="grid gap-4 md:grid-cols-2">
					<label class="flex items-center gap-2 text-sm">
						<Checkbox bind:checked={debugMode} />
						Debug mode
					</label>

					<label class="flex items-center gap-2 text-sm">
						<Checkbox bind:checked={showAll} />
						Show all submissions
					</label>
				</div>

				<label class="space-y-2 text-sm font-medium">
					<span>Include submission ID</span>

					<Input
						bind:value={includeId}
						placeholder="Optional submission ID"
					/>
				</label>

				<div>
					<p class="mb-2 text-sm font-medium">Status</p>

					<div class="flex flex-wrap gap-4">
						{#each ["approved", "pending", "denied"] as status}
							<label class="flex items-center gap-2 text-sm">
								<Checkbox
									checked={selectedStatuses.includes(status)}
									onCheckedChange={(checked) => {
										if (checked === true) {
											selectedStatuses = [
												...selectedStatuses,
												status,
											];
										} else {
											selectedStatuses =
												selectedStatuses.filter(
													(value) => value !== status,
												);
										}
									}}
								/>

								<span class="capitalize">{status}</span>
							</label>
						{/each}
					</div>
				</div>

				<div>
					<p class="mb-2 text-sm font-medium">Issue types</p>

					<div class="grid gap-2 md:grid-cols-2">
						{#each issueTypes as issue}
							<label class="flex items-center gap-2 text-sm">
								<Checkbox
									checked={selectedIssueTypes.includes(issue)}
									onCheckedChange={(checked) => {
										if (checked === true) {
											selectedIssueTypes = [
												...selectedIssueTypes,
												issue,
											];
										} else {
											selectedIssueTypes =
												selectedIssueTypes.filter(
													(value) => value !== issue,
												);
										}
									}}
								/>

								<span class="capitalize">
									{formatIssue(issue)}
								</span>
							</label>
						{/each}
					</div>
				</div>

				<div class="flex justify-end gap-2">
					<Button
						type="button"
						variant="ghost"
						onclick={resetFilters}
					>
						Reset
					</Button>

					<Button type="button" onclick={applyServerFilters}>
						Apply filters
					</Button>
				</div>
			</Card>
		{/if}

		<div class="flex flex-wrap gap-2 border-b">
			<Button
				type="button"
				variant={activeTab === "all" ? "default" : "ghost"}
				onclick={() => (activeTab = "all")}
			>
				All issues ({filteredSubmissions.length})
			</Button>

			<Button
				type="button"
				variant={activeTab === "payment" ? "default" : "ghost"}
				onclick={() => (activeTab = "payment")}
			>
				Payment ({paymentIssues.length})
			</Button>

			<Button
				type="button"
				variant={activeTab === "email" ? "default" : "ghost"}
				onclick={() => (activeTab = "email")}
			>
				Email ({emailIssues.length})
			</Button>

			<Button
				type="button"
				variant={activeTab === "ticket" ? "default" : "ghost"}
				onclick={() => (activeTab = "ticket")}
			>
				Ticket ({ticketIssues.length})
			</Button>
		</div>

		{#if visibleSubmissions.length === 0}
			<Card class="p-8 text-center text-muted-foreground">
				No submission issues found.
			</Card>
		{:else}
			<div class="grid gap-4">
				{#each visibleSubmissions as submission (submission.id)}
					<Card class="space-y-5 p-5">
						<div
							class="flex flex-col justify-between gap-4 md:flex-row"
						>
							<div>
								<h2 class="text-lg font-semibold">
									{submission.participant_name}
								</h2>

								<p class="text-sm text-muted-foreground">
									{submission.participant_email}
								</p>

								<p class="mt-1 text-xs text-muted-foreground">
									{submission.id}
								</p>
							</div>

							<div class="flex flex-wrap gap-2">
								<span
									class="rounded-full border px-2 py-1 text-xs capitalize"
								>
									{submission.status}
								</span>

								{#if hasPaymentIssue(submission)}
									<span
										class="rounded-full border border-destructive/40 bg-destructive/10 px-2 py-1 text-xs text-destructive"
									>
										Payment issue
									</span>
								{/if}

								{#if hasEmailIssue(submission)}
									<span
										class="rounded-full border px-2 py-1 text-xs"
									>
										Email issue
									</span>
								{/if}

								{#if hasTicketIssue(submission)}
									<span
										class="rounded-full border border-orange-300 px-2 py-1 text-xs text-orange-700"
									>
										Ticket issue
									</span>
								{/if}
							</div>
						</div>

						<div class="grid gap-4 text-sm md:grid-cols-4">
							<div>
								<p class="text-muted-foreground">Event</p>
								<p class="font-medium">
									{getEventName(submission)}
								</p>
							</div>

							<div>
								<p class="text-muted-foreground">Vehicle</p>
								<p class="font-medium">
									{submission.vehicle_year}
									{submission.vehicle_make}
									{submission.vehicle_model}
								</p>
							</div>

							<div>
								<p class="text-muted-foreground">Submitted</p>
								<p class="font-medium">
									{formatDate(submission.submitted_at)}
								</p>
							</div>

							<div>
								<p class="text-muted-foreground">Reviewed</p>
								<p class="font-medium">
									{formatDate(submission.reviewed_at)}
								</p>
							</div>
						</div>

						{#if submission.issues?.length}
							<div
								class="rounded-xl border border-yellow-300/50 bg-yellow-50 p-4 dark:bg-yellow-950/20"
							>
								<p class="font-medium">Issues detected</p>

								<ul class="mt-2 list-inside list-disc text-sm">
									{#each submission.issues as issue}
										<li class="capitalize">
											{formatIssue(issue)}
										</li>
									{/each}
								</ul>
							</div>
						{/if}

						<div class="flex flex-wrap gap-2">
							{#if hasPaymentIssue(submission)}
								<Button
									type="button"
									variant="outline"
									onclick={() =>
										checkPaymentStatus(submission)}
									disabled={checkingPayment}
								>
									{checkingPayment
										? "Checking…"
										: "Check payment"}
								</Button>

								<Button
									type="button"
									onclick={() =>
										openCreatePayment(submission)}
								>
									Create payment
								</Button>
							{/if}

							{#if hasEmailIssue(submission) && submission.status === "approved"}
								<Button
									type="button"
									variant="outline"
									onclick={() =>
										resendApprovalEmail(submission)}
									disabled={resendingEmail}
								>
									{resendingEmail
										? "Sending…"
										: "Resend approval email"}
								</Button>
							{/if}
						</div>

						<div
							class="flex flex-wrap gap-3 border-t pt-3 text-xs text-muted-foreground"
						>
							{#if submission.checkout_session_id}
								<span>
									Session:
									{submission.checkout_session_id.slice(
										0,
										8,
									)}…
								</span>
							{/if}

							{#if submission.payment_intent_id}
								<span>
									Payment:
									{submission.payment_intent_id.slice(0, 8)}…
								</span>
							{/if}
						</div>
					</Card>
				{/each}
			</div>
		{/if}
	</div>
{/if}

{#if showPaymentStatus && paymentStatus}
	<div
		class="fixed inset-0 z-50 overflow-y-auto bg-background/80 p-4 backdrop-blur-sm"
	>
		<div class="mx-auto max-w-md">
			<Card class="space-y-5 p-5">
				<div class="flex items-start justify-between">
					<div>
						<h2 class="text-lg font-semibold">Payment status</h2>

						<p class="text-sm text-muted-foreground">
							{selectedSubmission?.participant_name}
						</p>
					</div>

					<Button
						type="button"
						variant="ghost"
						onclick={() => (showPaymentStatus = false)}
					>
						Close
					</Button>
				</div>

				<div class="space-y-3 text-sm">
					<div class="flex justify-between">
						<span class="text-muted-foreground"> Has payment </span>

						<strong>
							{paymentStatus.has_payment ? "Yes" : "No"}
						</strong>
					</div>

					{#if paymentStatus.payment_status}
						<div class="flex justify-between">
							<span class="text-muted-foreground"> Status </span>

							<strong>
								{paymentStatus.payment_status}
							</strong>
						</div>
					{/if}

					{#if paymentStatus.payment_amount}
						<div class="flex justify-between">
							<span class="text-muted-foreground"> Amount </span>

							<strong>
								{(paymentStatus.payment_amount / 100).toFixed(
									2,
								)}
								{paymentStatus.payment_currency?.toUpperCase()}
							</strong>
						</div>
					{/if}

					{#if paymentStatus.email_sent_at}
						<div class="flex justify-between">
							<span class="text-muted-foreground">
								Email sent
							</span>

							<strong>
								{formatDate(paymentStatus.email_sent_at)}
							</strong>
						</div>
					{/if}
				</div>

				{#if paymentStatus.error_message}
					<p
						class="rounded-lg border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive"
					>
						{paymentStatus.error_message}
					</p>
				{/if}

				{#if paymentStatus.checkout_url}
					<Button
						type="button"
						class="w-full"
						onclick={() =>
							window.open(paymentStatus?.checkout_url, "_blank")}
					>
						Open checkout
					</Button>
				{/if}
			</Card>
		</div>
	</div>
{/if}

{#if showCreatePayment && selectedSubmission}
	<div
		class="fixed inset-0 z-50 overflow-y-auto bg-background/80 p-4 backdrop-blur-sm"
	>
		<div class="mx-auto max-w-md">
			<Card class="space-y-5 p-5">
				<div class="flex items-start justify-between">
					<div>
						<h2 class="text-lg font-semibold">
							Create payment link
						</h2>

						<p class="text-sm text-muted-foreground">
							{selectedSubmission.participant_name}
						</p>
					</div>

					<Button
						type="button"
						variant="ghost"
						onclick={() => (showCreatePayment = false)}
					>
						Close
					</Button>
				</div>

				{#if loadingPrices}
					<p class="py-6 text-center text-sm text-muted-foreground">
						Loading ticket prices…
					</p>
				{:else}
					<label class="space-y-2 text-sm font-medium">
						<span>Ticket price</span>

						<select
							class="w-full rounded-md border bg-background px-3 py-2"
							bind:value={selectedPriceId}
						>
							<option value="">Choose a ticket type</option>

							{#each prices as price (price.id)}
								<option value={price.id}>
									{price.nickname || "Ticket"} —
									{(price.unit_amount / 100).toFixed(2)}
									{price.currency.toUpperCase()}
								</option>
							{/each}
						</select>
					</label>

					<div class="flex justify-end gap-2">
						<Button
							type="button"
							variant="outline"
							onclick={() => (showCreatePayment = false)}
						>
							Cancel
						</Button>

						<Button
							type="button"
							onclick={createPayment}
							disabled={!selectedPriceId || creatingPayment}
						>
							{creatingPayment
								? "Creating…"
								: "Create payment link"}
						</Button>
					</div>
				{/if}
			</Card>
		</div>
	</div>
{/if}
