// ui/src/lib/components/ui/infinite-moving-cards.svelte
<script lang="ts" module>
	export interface TestimonialItem {
		quote: string;
		name: string;
		title: string;
	}

	export interface LogoItem {
		name: string;
		logoUrl: string;
		link?: string;
	}

	export type InfiniteMovingItem = TestimonialItem | LogoItem;
</script>

<script lang="ts">
	type Direction = 'left' | 'right';
	type Speed = 'fast' | 'normal' | 'slow';
	type Variant = 'testimonial' | 'logo';

	interface Props {
		items: InfiniteMovingItem[];
		direction?: Direction;
		speed?: Speed;
		pauseOnHover?: boolean;
		className?: string;
		variant?: Variant;
	}

	let {
		items,
		direction = 'left',
		speed = 'fast',
		pauseOnHover = true,
		className = '',
		variant = 'testimonial'
	}: Props = $props();

	const durationMap: Record<Speed, string> = {
		fast: '20s',
		normal: '40s',
		slow: '80s'
	};

	let duplicatedItems = $derived([...items, ...items]);
	let animationDuration = $derived(durationMap[speed]);
	let animationDirection = $derived(direction === 'left' ? 'normal' : 'reverse');

	function isLogoItem(item: InfiniteMovingItem): item is LogoItem {
		return 'logoUrl' in item;
	}
</script>

<div
	class={[
		'scroller relative z-20 max-w-7xl overflow-hidden [mask-image:linear-gradient(to_right,transparent,white_20%,white_80%,transparent)]',
		pauseOnHover && 'pause-on-hover',
		className
	]}
	style={`--animation-duration: ${animationDuration}; --animation-direction: ${animationDirection}; --gap: 1rem;`}
>
	<ul class="track">
		{#each duplicatedItems as item, idx (`${isLogoItem(item) ? item.name : item.name}-${idx}`)}
			{#if variant === 'logo' && isLogoItem(item)}
				{@const logo = item}
				<li
					aria-hidden={idx >= items.length}
					class="relative shrink-0 rounded-xl border border-neutral-200 bg-white dark:border-neutral-800 dark:bg-neutral-900"
				>
					{#if logo.link}
						<a href={logo.link} target="_blank" rel="noopener noreferrer" class="block">
							<div class="flex h-40 w-60 items-center justify-center p-4">
								<img
									src={logo.logoUrl}
									alt={logo.name}
									class="max-h-full max-w-full object-contain transition-all duration-300 hover:grayscale"
								/>
							</div>
						</a>
					{:else}
						<div class="flex h-40 w-60 items-center justify-center p-4">
							<img
								src={logo.logoUrl}
								alt={logo.name}
								class="max-h-full max-w-full object-contain transition-all duration-300 hover:grayscale"
							/>
						</div>
					{/if}
				</li>
			{:else}
				{@const testimonial = item as TestimonialItem}
				<li
					aria-hidden={idx >= items.length}
					class="relative w-[350px] max-w-full shrink-0 rounded-2xl border border-b-0 border-zinc-200 bg-[linear-gradient(180deg,#fafafa,#f5f5f5)] px-8 py-6 md:w-[450px] dark:border-zinc-700 dark:bg-[linear-gradient(180deg,#27272a,#18181b)]"
				>
					<blockquote>
						<div
							aria-hidden="true"
							class="pointer-events-none absolute -left-0.5 -top-0.5 -z-1 h-[calc(100%_+_4px)] w-[calc(100%_+_4px)] select-none"
						></div>

						<span class="relative z-20 text-sm leading-[1.6] font-normal text-neutral-800 dark:text-gray-100">
							{testimonial.quote}
						</span>

						<div class="relative z-20 mt-6 flex flex-row items-center">
							<span class="flex flex-col gap-1">
								<span class="text-sm leading-[1.6] font-normal text-neutral-500 dark:text-gray-400">
									{testimonial.name}
								</span>
								<span class="text-sm leading-[1.6] font-normal text-neutral-500 dark:text-gray-400">
									{testimonial.title}
								</span>
							</span>
						</div>
					</blockquote>
				</li>
			{/if}
		{/each}
	</ul>
</div>

<style>
	.track {
		display: flex;
		width: max-content;
		min-width: 100%;
		flex-wrap: nowrap;
		gap: var(--gap);
		padding-block: 1rem;
		animation: scroll var(--animation-duration) linear infinite;
		animation-direction: var(--animation-direction);
	}

	.pause-on-hover .track:hover {
		animation-play-state: paused;
	}

	@keyframes scroll {
		to {
			transform: translateX(calc(-50% - var(--gap) / 2));
		}
	}
</style>

// src/components/ui/infinite-moving-cards.tsx
import { cn } from "~/lib/utils";
import React, { useEffect, useState } from "react";

// Type for testimonial items
export interface TestimonialItem {
	quote: string;
	name: string;
	title: string;
}

// Type for logo items
export interface LogoItem {
	name: string;
	logoUrl: string;
	link?: string;
}

// Union type for both item types
export type InfiniteMovingItem = TestimonialItem | LogoItem;

// Type guard to check if item is a logo
function isLogoItem(item: InfiniteMovingItem): item is LogoItem {
	return 'logoUrl' in item;
}

export const InfiniteMovingCards = ({
	items,
	direction = "left",
	speed = "fast",
	pauseOnHover = true,
	className,
	variant = "testimonial",
}: {
	items: InfiniteMovingItem[];
	direction?: "left" | "right";
	speed?: "fast" | "normal" | "slow";
	pauseOnHover?: boolean;
	className?: string;
	variant?: "testimonial" | "logo";
}) => {
	const containerRef = React.useRef<HTMLDivElement>(null);
	const scrollerRef = React.useRef<HTMLUListElement>(null);

	useEffect(() => {
		addAnimation();
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);
	const [start, setStart] = useState(false);
	function addAnimation() {
		if (containerRef.current && scrollerRef.current) {
			const scrollerContent = Array.from(scrollerRef.current.children);

			scrollerContent.forEach((item) => {
				const duplicatedItem = item.cloneNode(true);
				if (scrollerRef.current) {
					scrollerRef.current.appendChild(duplicatedItem);
				}
			});

			getDirection();
			getSpeed();
			setStart(true);
		}
	}
	const getDirection = () => {
		if (containerRef.current) {
			if (direction === "left") {
				containerRef.current.style.setProperty(
					"--animation-direction",
					"forwards",
				);
			} else {
				containerRef.current.style.setProperty(
					"--animation-direction",
					"reverse",
				);
			}
		}
	};
	const getSpeed = () => {
		if (containerRef.current) {
			if (speed === "fast") {
				containerRef.current.style.setProperty("--animation-duration", "20s");
			} else if (speed === "normal") {
				containerRef.current.style.setProperty("--animation-duration", "40s");
			} else {
				containerRef.current.style.setProperty("--animation-duration", "80s");
			}
		}
	};

	const renderItem = (item: InfiniteMovingItem, idx: number) => {
		if (variant === "logo" && isLogoItem(item)) {
			const content = (
				<div className="flex items-center justify-center h-20 w-40 p-4">
					<img
						src={item.logoUrl}
						alt={item.name}
						className="max-h-full max-w-full object-contain filter grayscale hover:grayscale-0 transition-all duration-300"
					/>
				</div>
			);

			return (
				<li
					key={item.name + idx}
					className="relative shrink-0 rounded-xl bg-white dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800"
				>
					{item.link ? (
						<a href={item.link} target="_blank" rel="noopener noreferrer" className="block">
							{content}
						</a>
					) : (
						content
					)}
				</li>
			);
		}

		// Default testimonial rendering
		const testimonialItem = item as TestimonialItem;
		return (
			<li
				className="relative w-[350px] max-w-full shrink-0 rounded-2xl border border-b-0 border-zinc-200 bg-[linear-gradient(180deg,#fafafa,#f5f5f5)] px-8 py-6 md:w-[450px] dark:border-zinc-700 dark:bg-[linear-gradient(180deg,#27272a,#18181b)]"
				key={testimonialItem.name + idx}
			>
				<blockquote>
					<div
						aria-hidden="true"
						className="user-select-none pointer-events-none absolute -top-0.5 -left-0.5 -z-1 h-[calc(100%_+_4px)] w-[calc(100%_+_4px)]"
					></div>
					<span className="relative z-20 text-sm leading-[1.6] font-normal text-neutral-800 dark:text-gray-100">
						{testimonialItem.quote}
					</span>
					<div className="relative z-20 mt-6 flex flex-row items-center">
						<span className="flex flex-col gap-1">
							<span className="text-sm leading-[1.6] font-normal text-neutral-500 dark:text-gray-400">
								{testimonialItem.name}
							</span>
							<span className="text-sm leading-[1.6] font-normal text-neutral-500 dark:text-gray-400">
								{testimonialItem.title}
							</span>
						</span>
					</div>
				</blockquote>
			</li>
		);
	};

	return (
		<div
			ref={containerRef}
			className={cn(
				"scroller relative z-20 max-w-7xl overflow-hidden [mask-image:linear-gradient(to_right,transparent,white_20%,white_80%,transparent)]",
				className,
			)}
		>
			<ul
				ref={scrollerRef}
				className={cn(
					"flex w-max min-w-full shrink-0 flex-nowrap gap-4 py-4",
					start && "animate-scroll",
					pauseOnHover && "hover:[animation-play-state:paused]",
				)}
			>
				{items.map((item, idx) => renderItem(item, idx))}
			</ul>
		</div>
	);
};
